### ISSUE TITLE
Error executing process > 'mixMHC2pred

### ISSUE THREAD

**Issue by beijish** [icbi-lab/nextNEOpi#10]
Good afternoon,
thanks for sharing nextNEOpi, it's a very useful resource. 
I am working on HPC (LMOD), using singularity, nextflow version 22.04.4., nextNEOpi v.1.3 & 1.3.2, hla-hd v.1.5.0, VEP v.105 & 106.1, hg38. 

It runs smoothly up to mixMHC2pred, when it gets stuck with the following error:

_Error executing process > 'mixMHC2pred (PB-16-002)'

Caused by:
  Process `mixMHC2pred (PB-16-002)` terminated with an error exit status (1)

Command executed:

  /XXX/work/MixMHC2pred/MixMHC2pred_unix \
      -i PB-16-002_peptides.fasta \
      -o PB-16-002_mixMHC2pred.tsv \
      -a DRB1_15_01 DRB1_12_01 DRB3_01_01 DRB5_01_01
  parse_mixMHC2pred.py \
      --vep_vcf PB-16-002_vep_somatic_gx.vcf.gz \
      --pep_fasta PB-16-002_peptides.fasta \
      --mixMHC2pred_result PB-16-002_mixMHC2pred.tsv \
      --out PB-16-002_mixMHC2pred_all.tsv \
      --sample_name PB-16-002_tumor \
      --normal_name PB-16-002_normal
  awk \
      '{
          if ($0 ~ /\#/) { print }
          else { if ($18 <= 2) { print } }
      }' PB-16-002_mixMHC2pred_all.tsv > PB-16-002_mixMHC2pred_filtered.tsv

Command exit status:
  1

Command output:
  Runing MixMHC2pred (v1.2) for peptide file: PB-16-002_peptides.fasta
  Imported 27848 peptides. Computing now the scores from each peptide.
  Finished the computations.

Command error:
  Traceback (most recent call last):
    File "/XXX/bin/parse_mixMHC2pred.py", line 181, in <module>
      out_file.write("\t".join(map(str, vcf_map[key].values())) + "\t" + line)
  KeyError: 'ENSG00000285238_ENST00000644480.2_911-912GAGAA/G'

Work dir:
  /XXX/work/89/b85145dc36f106bca16fa3f0c7007d

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line_

I have been trying for weeks to find out to understand where the problem is, my sys admins think it could be a glitch with parse_mixMHC2pred.py but I am not a python person to try and do this myself. I would really benefit from some help, please.
Thanks in advance

SV

**Comment by riederd** [comment]
Hi,
do you mind sharing/mailing the following files, so that I can check what happens:

```
/XXX/work/89/b85145dc36f106bca16fa3f0c7007d/PB-16-002_vep_somatic_gx.vcf.gz
/XXX/work/89/b85145dc36f106bca16fa3f0c7007d/PB-16-002_peptides.fasta
/XXX/work/89/b85145dc36f106bca16fa3f0c7007d/PB-16-002_mixMHC2pred.tsv
/XXX/work/89/b85145dc36f106bca16fa3f0c7007d/PB-16-002_mixMHC2pred.tsv
```

Thanks

**Comment by beijish** [comment]
Sure, see zipped folder, please let me know if you prefer me to send it by email.
Thank you a lot

SV
[Archive.zip](https://gith
[Archive.zip](https://github.com/icbi-lab/nextNEOpi/files/9243601/Archive.zip)
ub.com/icbi-lab/nextNEOpi/files/9243596/Archive.zip)

**Comment by riederd** [comment]
Thanks for reporting this issue.
There seem to occur rare situations where VEP can not assign a gene symbol to annotate a mutation, this caused the problem with our `mixMHC2pred` parser.

I fixed the problem now and made a new release.

You may also just download the fixed parser script from https://github.com/icbi-lab/nextNEOpi/raw/master/bin/parse_mixMHC2pred.py and place it into your `nextNEOpi` `bin` directory and resume the pipeline with the `-resume` command line option.

**Comment by beijish** [comment]
Lucky me who picked up the VEP exception!
Thank s a lot

Sara

On 3 Aug 2022, at 10:21, Dietmar Rieder ***@***.***> wrote:

﻿

Thanks for reporting this issue.
There seem to occur rare situations where VEP can not assign a gene symbol to annotate a mutation, this caused the problem with our mixMHC2pred parser.

I fixed the problem now and made a new release.

You may also just download the fixed parser script from https://github.com/icbi-lab/nextNEOpi/raw/master/bin/parse_mixMHC2pred.py and place it into your nextNEOpi bin directory and resume the pipeline with the -resume command line option.
