### ISSUE TITLE
immunogenicity_scoring

### ISSUE THREAD

**Issue by beijish** [icbi-lab/nextNEOpi#11]
Good evening,

pipeline completed but immunogenicity_scoring vails... I was wondering if you've been able to resolve "  // TODO: check why sometimes this fails: workaround ignore errors
    errorStrategy 'ignore'"
 ?

I suspect we're stuck with the same bit here. Happy to send more Information if useful.
BW

SV

**Comment by riederd** [comment]
Hi,

good to hear that the pipeline completed now.
I must admit that until now we did not come around to dig into this issue, as far as I remember it is an issue with the GBM model R code we use from https://github.com/vincentlaboratories/neoag/
If you can post the content of the work folder from the immunogenicity_scoring process I will see if I find some time to look into this.
