### ISSUE TITLE
Yara DNA vs RNA DBs

### ISSUE THREAD

**Issue by pintoa1-mskcc** [icbi-lab/nextNEOpi#12]
``Hi! 

I am trying to utlize your pipeline with hg19 instead of GRCh38. Because of this I am trying to recreate the yara references, but I have never used this tool before so I do not know what exactly to do. Mainly, my concern is the difference between the RNA and DNA references for yara? I had assumed I could simply run 

`yara_indexer $RefFasta`

but this would only give me one database, i'd assume for DNA not RNA. Why are there two databases needed and how can I make them for hg19?

**Comment by riederd** [comment]
Hello,

thanks for your interest in **nextNEOpi**.

You do not need to recreate the yara index. It is only used for HLA typing with `optitype`. Optitype comes with its own reference sequence specific for the HLA genes (see https://github.com/FRED-2/OptiType/tree/master/data)
