### ISSUE TITLE
Slow process in get_vhla step

### ISSUE THREAD

**Issue by KunFang93** [icbi-lab/nextNEOpi#17]
Hi

I am trying to run the pipeline locally. However, the pipeline run very slow in get_vhla step. This step already took more than 5 days. I wondered if this is normal situation or the pipeline fall into some weird loop...I attached nf.log and .nextflow.log file. Thanks for your help~
[nf.log](https://github.com/icbi-lab/nextNEOpi/files/9905341/nf.log)
[nextflow.log](https://github.com/icbi-lab/nextNEOpi/files/9905342/nextflow.log)

Best,
Kun

**Comment by riederd** [comment]
Hi,
thanks for your interest in nextNEOpi.

According your `.nextflow.log` the process `get_vhla` completed successfully.

```
Oct-26 14:38:02.363 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 117; name: get_vhla (Patient353_T1star); status: COMPLETED; exit: 0; error: -; workDir: /data/kun/ChenHZ_lab/Neoantigens/patient353/T1/work/22/ce89ac46b2ca9642858d62d0d9bc34]
```

It seems to hang at the `MarkDuplicates` process. Can you check the files in `/data/kun/ChenHZ_lab/Neoantigens/patient353/T1/work/89/1f1771d1843dfa04c9ab2159038b5a`?
Is there a file named `*_aligned_sort_mkdp.bam`? If yes is it growing in size?

Can you see (`ps -ax`) if any of the following processes/programs are currently running:
```
sambamba
samtools
gatk --java-options ${params.JAVA_Xmx} SetNmMdAndUqTags 
```
Thanks

**Comment by riederd** [comment]
see #16
