### ISSUE TITLE
Output file discriptions  

### ISSUE THREAD

**Issue by rezakj** [icbi-lab/nextNEOpi#22]
Hi, 

I have 2 questions:

1- Is there a better documantion of the output files?

2- In the "neoantigens/sample1/Class_II/" diretory the following files are missing:
sample1_MHC_Class_I_all_epitopes_ccf_ref_match.tsv, sample1_MHC_Class_I_filtered_ccf_ref_match.tsv. 
Do you know why is that?

**Comment by riederd** [comment]
Hi, thanks for your interest in `nextNEOpi`

@1 You can find more information in the supplemental material of our publication [https://doi.org/10.1093/bioinformatics/btab759](url)

@2 In the `Class_II` directory you should not find `MHC_Class_I` related/named files, because it is only for `MHC_Class_II` results.

**Comment by rezakj** [comment]
Oh sorry, I copy pasted the file name from class I but I meant this file (classII):

sample1_MHC_Class_II_all_epitopes_ccf_ref_match.tsv

There is only a fusion folder in it.

**Comment by riederd** [comment]
Can you attach the `.nextflow.log` file, so that I can check?

**Comment by rezakj** [comment]
Attached.

[slurm-20852100.out.log](https://github.com/icbi-lab/nextNEOpi/files/11103168/slurm-20852100.out.log)

**Comment by riederd** [comment]
It seems that you did not specify the path to your local *HLA-HD* installation.

Your `slurm-20852100.out.log`, which bwt is not the `.nextflow.log`, shows:
` WARN: WARNING: HLAHD not available - can not predict Class II neoepitopes`

Here is the relevant section from the [README.md](https://github.com/icbi-lab/nextNEOpi/#readme):

> Optional but recommended: Due to license restrictions you may also need to download and install HLA-HD by your own, and set the installation path in conf/params.config. If HLA-HD is not available Class II neoepitopes will NOT be predicted

Unfortunately we are not allowed to bundle and distribute HLA-HD, therefore `nextNEOpi` users need to install it manually on their system if they want to also predict Class II neoepitopes.

HTH, closing this ticket for now

**Comment by rezakj** [comment]
Thank you. 
Reza
