### ISSUE TITLE
Error Unknown method

### ISSUE THREAD

**Issue by Magisterh1** [icbi-lab/nextNEOpi#3]
Hi! I tried to use nextNEOpi and received the following error:

Unknown method `div` on ConfigObject type

My code:
nextflow run nextNEOpi.nf --readsTumor /work/Projects/Neoantigens_nextNEOpi/testdata/Tumor_ERR8313719_1.fastq /work/Projects/Neoantigens_nextNEOpi/testdata/Tumor_ERR8313719_2.fastq --readsNormal /work/Projects/Neoantigens_nextNEOpi/testdata/Normal_ERR8313721_1.fastq /work/Projects/Neoantigens_nextNEOpi/testdata/Normal_ERR8313721_2.fastq -config conf/params.config --outputDir /data/results/nextNEOpi/myResults --trim_adapters true --use_NetChop false -profile conda,cluster -resume

Can you please help me to solve this issue?

Thank you!! Best, GH

**Comment by riederd** [comment]
Please try to use the following format to provide paired end reads on the command line, as it si explained in the Readme under "**FASTQ raw reads:**":

`--readsTumor  /work/Projects/Neoantigens_nextNEOpi/testdata/Tumor_ERR8313719_1,2}.fastq`
`--readsNormal /work/Projects/Neoantigens_nextNEOpi/testdata/Normal_ERR8313721_{1,2}.fastq`

alternatively, you may use a batch file to pass on the reads (which will be the only way in future versions anyway). 

Hope this helps

**Comment by Magisterh1** [comment]
Thank you! I tried to run nextNEOpi.nf using the batch file and using your recommendation from above with and without quotes. However, I always end up with "Unknown method `div` on ConfigObject type". Do you have an other suggestion for me? THX

**Comment by Magisterh1** [comment]
[nextflow.log](https://github.com/icbi-lab/nextNEOpi/files/8097163/nextflow.log)

**Comment by riederd** [comment]
Thanks, can you also post the `/work/Projects/Neoantigens_nextNEOpi/nextNEOpi/conf/params.config` file.

**Comment by riederd** [comment]
..and please check also the cluster profile settings in `/work/Projects/Neoantigens_nextNEOpi/nextNEOpi/conf/profiles.config` as you are specify ` -profile conda,cluster` . You might need to adjust the cluster profile to match your environment . See also the **Profiles: cluster** section in the Readme

**Comment by Magisterh1** [comment]
ok, done, unfortunately only the wording of the error changed: Unknown method invocation `div` on ConfigObject type

**Comment by Magisterh1** [comment]
OK, what worked so far: 1. update nextflow, 2. add quotes to paths in params.config.
Now I have to solve some conda problems... THX for your help!!
