### ISSUE TITLE
Check if files exist, better error message than 'Cannot get property 'simpleName' on null object'

### ISSUE THREAD

**Issue by richelbilderbeek** [icbi-lab/nextNEOpi#36]
Dear nextNEOpi maintainers,

Here I submit a suggestion as both me and a colleague independently ran into the same problem and both of us would enjoy a better error message.

Below I supply:

 * Short description of the problem
 * Suggested solution
 * Detailed description with [reprex](https://stackoverflow.com/help/minimal-reproducible-example)

I hope you'll agree that this would make nextNEIpi even better :-)

Thanks and cheers, Richel Bilderbeek

## Short description of the problem

[Line L4696 in nextNEOpi.nf](https://github.com/icbi-lab/nextNEOpi/blob/master/nextNEOpi.nf#L4696) ...

```
val yaraIdx from Channel.value(reference.YaraIndexDNA[0].simpleName)
```

... does not check if the array `YaraIndexDNA` has actual elements, which gives an uninformative error if the reference files needed do not exists:

```
Cannot get property 'simpleName' on null object

 -- Check script 'nextNEOpi.nf' at line: 4696 or see '.nextflow.log' file for more details
```

(from [this GitHub Actions error log](https://github.com/richelbilderbeek/nextNEOpi_example_1/actions/runs/5584180107/jobs/10205295456#step:5:237), need to be logged in into GitHub before being able to see it)

## Suggested solution

Make [Line L4696 in nextNEOpi.nf](https://github.com/icbi-lab/nextNEOpi/blob/master/nextNEOpi.nf#L4696) check if all the files it expects are in place. Maybe that line is not the best place to do so; you are the experts here.

## Detailed description with [reprex](https://stackoverflow.com/help/minimal-reproducible-example)

To reproduce this example, do (and all code is in [this GitHub repository](https://github.com/richelbilderbeek/nextNEOpi_example_1)):

```
git clone https://github.com/richelbilderbeek/nextNEOpi_example_1
cd nextNEOpi_example_1
./scripts/run.sh
```

(which is the same as [done in the GitHub Actions script](https://github.com/richelbilderbeek/nextNEOpi_example_1/blob/master/.github/workflows/run.yaml#L31))

As [there is no small/testing data yet](https://github.com/icbi-lab/nextNEOpi/issues/33), I try to create the `reference` folders myself, using the script [create_fake_references.sh](https://github.com/richelbilderbeek/nextNEOpi_example_1/blob/master/scripts/create_fake_references.sh), which only copies the a file called [hg38.len](https://github.com/richelbilderbeek/nextNEOpi_example_1/blob/master/scripts/hg38.len) to the right folder. 

The error caused is this approach is, of course, that the actual reference data is not created. And here I would expect a proper error message.

One cause argue that 'one should not do that', but my colleague had the same error from trying out to get nextNEOpi running. I am unsure what he did, but he was not creating a reprex like I did. Also for him, I would expect a proper error message.

**Comment by riederd** [comment]
Thanks for reporting. I'm implementing a fix
