### ISSUE TITLE
Unable to parse config file: '/a/b/nextNEOpi/conf/params.config'

### ISSUE THREAD

**Issue by rashidma** [icbi-lab/nextNEOpi#42]
I have installed nextNEOpi latest version from github and all its requirements. I am using Ubuntu 18.04.

1) nextflow -version
      _N E X T F L O W
      version 23.04.3 build 5875
      created 11-08-2023 18:37 UTC (21:37 ADT)
      cite doi:10.1038/nbt.3820
      http://nextflow.io_
2) java -version
_openjdk version "11.0.19" 2023-04-18
OpenJDK Runtime Environment (build 11.0.19+7-post-Ubuntu-0ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.19+7-post-Ubuntu-0ubuntu118.04.1, mixed mode, sharing)_
3) singularity --version
_2.4.2-dist_

**The command I run is as below:**
_NXF_VER=22.10.8 nextflow run ./nextNEOpi.nf \
	 --batchFile /media/mamoon/30806115-9b80-48b5-a937-40a7b4922f67/Data/NRC21R-082-03/Analysis/nextNEOpi/demo/batch_fastq.csv \
	 -config conf/params.config \
	 --outputDir /media/mamoon/30806115-9b80-48b5-a937-40a7b4922f67/Data/NRC21R-082-03/Analysis/nextNEOpi/demo/testresult \
	 --trim_adapters true \
	 --trim_adapters_RNAseq true \
	 --use_NetChop false \
	 -profile singularity \
	 -resume_

**It gives following error in the log file:**

_Sep-11 12:37:13.244 [main] DEBUG nextflow.cli.Launcher - $> nextflow run ./nextNEOpi.nf --batchFile /media/mamoon/30806115-9b80-48b5-a937
-40a7b4922f67/Data/NRC21R-082-03/Analysis/nextNEOpi/demo/batch_fastq.csv -config conf/params.config --outputDir /media/mamoon/30806115-9b
80-48b5-a937-40a7b4922f67/Data/NRC21R-082-03/Analysis/nextNEOpi/demo/testresult --trim_adapters true --trim_adapters_RNAseq true --use_Ne
tChop false -profile singularity -resume
Sep-11 12:37:13.329 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 22.10.8
Sep-11 12:37:13.370 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; embedded=false; plugins-dir=/home
/mamoon/.nextflow/plugins; core-plugins: nf-amazon@1.11.5,nf-azure@0.14.3,nf-codecommit@0.1.2,nf-console@1.0.4,nf-ga4gh@1.0.5,nf-google@1
.4.6,nf-tower@1.5.7-patch0,nf-wave@0.5.5
Sep-11 12:37:13.384 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Sep-11 12:37:13.386 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Sep-11 12:37:13.390 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.4.1 in 'deployment' mode
Sep-11 12:37:13.405 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
Sep-11 12:37:13.430 [main] DEBUG nextflow.config.ConfigBuilder - User config file: /media/mamoon/30806115-9b80-48b5-a937-40a7b4922f67/sof
tware/nextNEOpi/conf/params.config
Sep-11 12:37:13.431 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /media/mamoon/30806115-9b80-48b5-a937-40a7b4922f67/
software/nextNEOpi/conf/params.config
Sep-11 12:37:13.464 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `singularity`
**Sep-11 12:37:14.805 [main] ERROR nextflow.cli.Launcher - Unable to parse config file: '/media/mamoon/30806115-9b80-48b5-a937-40a7b4922f67/software/nextNEOpi/conf/params.config'**

  No signature of method: groovy.util.ConfigObject.div() is applicable for argument types: (Integer) values: [30806115]
  Possible solutions: min(groovy.lang.Closure), is(java.lang.Object), drop(int), wait(), size(), any()

groovy.lang.MissingMethodException: No signature of method: groovy.util.ConfigObject.div() is applicable for argument types: (Integer) va
lues: [30806115]
Possible solutions: min(groovy.lang.Closure), is(java.lang.Object), drop(int), wait(), size(), any()
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:70)_

Please let me know possible suggestions to solve this issue.
Thanks a lot

**Comment by riederd** [comment]
Did you make any changes to the config file?

**Comment by riederd** [comment]
No it should be a problem, as long it is syntactically correct.

**Comment by rashidma** [comment]
The changes to params.config are below:
// resourcesBaseDir = projectDir.toRealPath() + "/resources"
resourcesBaseDir = /Data/nextNEOpi

// run CNVkit
  CNVkit = false

Thats all.
Thank you for your time.

**Comment by rashidma** [comment]
Oh that silly mistake. It is good to go now.
Thank you

**Comment by riederd** [comment]
Glad I could help
