### ISSUE TITLE
Pipeline complete but missing output file(s) for immunogenicity scoring

### ISSUE THREAD

**Issue by amoschoomy** [icbi-lab/nextNEOpi#45]
Hello, I managed to run the pipeline on the sample test data. But unfortunately it is missing one of the output files expected by the process immunogencity scoring

`[f4/f6a60c] NOTE: Missing output file(s) `sample1_Class_I_immunogenicity.tsv` expected by process `immunogenicity_scoring (sample1)` -- Error is ignored`

```
Sep-15 11:12:19.578 [Task submitter] INFO  nextflow.Session - [f4/f6a60c] Submitted process > immunogenicity_scoring (sample1)
Sep-15 11:12:20.528 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 557; name: immunogenicity_scoring (sample1); status: COMPLETED; exit: 0; error: -; workDir: /home/uqachoo1/nextNEOpi-1.4.0/work/f4/f6a60c58002a7237fff929c7d11a25]
Sep-15 11:12:20.528 [Task monitor] DEBUG nextflow.processor.TaskProcessor - Process `immunogenicity_scoring (sample1)` is unable to find [UnixPath]: `/home/uqachoo1/nextNEOpi-1.4.0/work/f4/f6a60c58002a7237fff929c7d11a25/sample1_Class_I_immunogenicity.tsv` (pattern: `sample1_Class_I_immunogenicity.tsv`)
Sep-15 11:12:20.533 [Task monitor] INFO  nextflow.processor.TaskProcessor - [f4/f6a60c] NOTE: Missing output file(s) `sample1_Class_I_immunogenicity.tsv` expected by process `immunogenicity_scoring (sample1)` -- Error is ignored
```

**Comment by amoschoomy** [comment]
Update: So I rerun the pipeline but without the `resume` parameters and everything is working fine again. Maybe some tips on how to deal with this kind of issue? Previously when I reran it but while still including the `resume` parameters it just throws off an error that were totally unrelated to the issue I had.

Much appreciated for the help before I were to run any actual real data on here! Thanks!

**Comment by riederd** [comment]
Hi, this is not an issue. Unfortunately the immunogenicity_scoring code, which is not developed or maintained by us, is sometimes failing, we are expecting this and so this error is ignored as you can see from:

```
[f4/f6a60c] NOTE: Missing output file(s) sample1_Class_I_immunogenicity.tsv expected by processimmunogenicity_scoring (sample1) -- Error is ignored
```

**Comment by riederd** [comment]
I'm closing this issue now. Please feel free to reopen in case something related pops up.
