### ISSUE TITLE
work folder

### ISSUE THREAD

**Issue by amoschoomy** [icbi-lab/nextNEOpi#47]
Hi, I'm running into disk quota error in my hpc while running the pipeline. I checked in my HPC, turns out while the pipeline is running, nextNEOpi is writing data into the folder named `work` that is enormously large. How do I prevent this from using up my disk quota? I've already set up `$TMPDIR` (there's a default tmp directory created by our HPC everytime a batch script is submitted) as shown below but the `work` folder still gets written in my HPC.

```bash
export JAVA_CMD=/home/uqachoo1/mambaforge/envs/env/bin/java
export NXF_OPTS='-Xms1g -Xmx4g'

nextflow run nextNEOpi.nf \
    --batchFile /home/uqachoo1/nextNEOpi-1.4.0/wesmRNA_batchFile_fastq.csv \
    -config conf/params.config \
    --outputDir /QRISdata/Q6373/results/test_results \
    --trim_adapters true \
    --trim_adapters_RNAseq true \
    --use_NetChop false \
    --tmpDir $TMPDIR \
    -profile singularity,cluster \
    --accept_license \
    --MIXCR_lic /home/uqachoo1/nextNEOpi-1.4.0/mi.license  \
```
Much thanks!

**Comment by riederd** [comment]
Hi,

the option `--tmpDir` does not set the nextflow `work` directory. You may want to use the nextflow `-work-dir` command line option to specify a custom `workdir`. See also: https://www.nextflow.io/docs/latest/cli.html?highlight=work-dir#run
