### ISSUE TITLE
Lacking VEP cache file Homo_sapiens.GRCh38.dna.toplevel.fa.gz

### ISSUE THREAD

**Issue by wwoskie** [icbi-lab/nextNEOpi#48]
VEP cache has been (successfuly?) pulled during installation process and spawned a bunch of files. However, on the next start pipeline throws:
`ERROR: Resource file does not exist: /media/alex/_data_ext/nextNEOpi/resources/databases/vep_cache/homo_sapiens/110_GRCh38/Homo_sapiens.GRCh38.dna.toplevel.fa.gz
Please check the references resource file settings in conf/resources.config`

`vep_cache/Plugins/` and `vep_cache/homo_sapiens/110_GRCh38` seem to be populated too

Thanks!

**Comment by riederd** [comment]
The file in question should exist:
```
$ ls -l 110_GRCh38/*.gz
-rw-r--r-- 1 rieder bioinf 950947839 Jul 21 15:56 110_GRCh38/Homo_sapiens.GRCh38.dna.toplevel.fa.gz
```

can you check if it is there?
```
ls -l /media/alex/_data_ext/nextNEOpi/resources/databases/vep_cache/homo_sapiens/110_GRCh38/Homo_sapiens.GRCh38.dna.toplevel.fa.gz
```

if it is, can you check if there is the installation check file?

```
ls -la /media/alex/_data_ext/nextNEOpi/resources/databases/vep_cache/.homo_sapiens_GRCh38_110_cache_ok.chck
```

**Comment by wwoskie** [comment]
Actually, I've just downloaded it manually from http://ftp.ensembl.org/pub/current_fasta/homo_sapiens/dna/
However, check file exists and was created way earlier (Sep 3rd) 

`╰─➤  ls -la /media/alex/_data_ext/nextNEOpi/resources/databases/vep_cache/.homo_sapiens_GRCh38_110_cache_ok.chck                                                                              [2023-09-20 | 13:38]
-rw-rw-r-- 1 alex alex 3 Sep 19 23:56 /media/alex/_data_ext/nextNEOpi/resources/databases/vep_cache/.homo_sapiens_GRCh38_110_cache_ok.chck`

**Comment by riederd** [comment]
Can you check your `.nextflow.log*` file(s) and find the `workdir` for the process called `installVEPcache` and post the `vep_errors.txt` file therein?

**Comment by riederd** [comment]
Do you have any `VEP_*` variable in your environment set? If yes, try to `unset VEP_[your_vars]` and then enter the workdir for the `installVEPcache` and run the process manually again using `bash .command.run`
