### ISSUE TITLE
Error executing process with NeoFuse

### ISSUE THREAD

**Issue by antaralabiba97** [icbi-lab/nextNEOpi#5]
Hi,

I came across your pipeline not long ago and found it would be great for my research so I am really keen to make sure I can get it running.

I set the pipeline up and did not input the HLA-HD file as I wanted to first make sure I could get the pipeline running to predict MHCI neoepitopes first. The only thing I did change was in the process.conf file where I changed the CPU usage for all processes to 40. 

I have attached the HTML file detailing the error which stopped the pipeline running at the NeoFuse stage. I went and had a look at the "sample1_MHCI_final.log" file as detailed in the error and the ".command.sh" script file in the working directory stated in the pdf file of the error which I have attached. In the pdf file the first line of the error has been omitted when I converted from HTML to pdf but it stated "Error executing process > 'Neofuse (sample1)".

I was happy that it was running smoothly and the prepoccessing steps had been completed successfully however, unfortunaley an error arised. I am actually not sure how to resolve the error stated and would really appreciate any help. 

Thank you in advance!

[Nextflow Workflow Report.pdf](https://github.com/icbi-lab/nextNEOpi/files/8769967/Nextflow.Workflow.Report.pdf)
[sample1_MHCI_final.log](https://github.com/icbi-lab/nextNEOpi/files/8769968/sample1_MHCI_final.log)
<img width="1242" alt="Screenshot 2022-05-25 at 10 34 22" src="https://user-images.githubusercontent.com/80478944/170236231-52e4c43f-1b9d-44ca-b8c9-260e068e013e.png">

**Comment by riederd** [comment]
Hi, I'm sorry that you are running into this troubles.

In order to sort this out I'd need some more information:
* Please tell us which version of nextNEOpi you are running
* Post the `.nextflow.log` file from the failed run.
* Post the `.command.run` file from the `/data/SBCS-BessantLab/Antara/nextNEOpi/work/a9/f5d9ded3bc5bc9dfbb2f33b7f58074`

Thanks

**Comment by antaralabiba97** [comment]
Thank you for your prompt response. 

I am using version nextNEOpi_v1.3.1 which I believe is the latest? I set this up on 21st of May using the latest documents and data available on GitHub. Also, I am running only one sample at the moment from the TESLA consortium data  used to benchmark your pipeline. I have WES normal and tumor and tumor rnaseq data. 

I have attached the files you have asked for. Just changed the extension from .run to .txt so I can attach it here.

Please let me know if you require any other info.  

Thank you.

[nextflow.log](https://github.com/icbi-lab/nextNEOpi/files/8770540/nextflow.log)
[command.run.txt](https://github.com/icbi-lab/nextNEOpi/files/8770548/command.run.txt)

**Comment by riederd** [comment]
Thanks for the information.
We are checking the relevant code in NEOfuse and try to understand why you get this error. Can you help us meanwhile with the following:

* post the following log file `/data/SBCS-BessantLab/Antara/nextNEOpi/work/a9/f5d9ded3bc5bc9dfbb2f33b7f58074/sample1/LOGS/sample1_8_MHCFlurry.log`
* check if `/data/SBCS-BessantLab/Antara/nextNEOpi/work/a9/f5d9ded3bc5bc9dfbb2f33b7f58074/sample1/NeoFuse/tmp/MHC_I/sample1_8_NEK11_ALDH1L1_1_8.tsv` exists
* rerun  (use `-resume`) with a smaller number of CPUs in NEOfuse (e.g. 8)

**Comment by antaralabiba97** [comment]
Hi, I have run the above and have attached what the output looks like. Please let me know the next stop. Thank you again! Really appreciate the help

 
<img width="1452" alt="Screenshot 2022-05-25 at 16 26 36" src="https://user-images.githubusercontent.com/80478944/170299926-4a7d3986-2bb1-465a-953f-8a8bf42de00d.png">

<img width="1156" alt="Screenshot 2022-05-25 at 16 33 50" src="https://user-images.githubusercontent.com/80478944/170300970-55ba173d-0f47-4479-a696-c7222ee00aee.png">

**Comment by riederd** [comment]
Ok, it seems that in principle mhcflurry works. Let's see if your run with less CPUs completes.

**Comment by antaralabiba97** [comment]
Hi,

So I was having issues with the jobs I had submitted to run on the cluster so decided to kill the previous runs and start fresh with the amended CPU 8 defined for NeoFuse. I set up the directory as I did before but noticed this time the link to the resources file on your GitHub is unreachable? So I used the resources folder I had already created. However, when I run the pipeline again there is no route to the host to pull the singularity image ...(attached screenshot). Added the nextflow log too.

I understand this is a different issue and if you would rather me post on a new thread please let me know! Very keen to get this pipeline working and looking forward to hopefully doing this soon! 

Thank you!

<img width="1042" alt="Screenshot 2022-05-25 at 22 57 43" src="https://user-images.githubusercontent.com/80478944/170374562-d700ca6e-fad5-49d7-b84e-0d1e012c78bc.png">

[nextflow.log](https://github.com/icbi-lab/nextNEOpi/files/8774781/nextflow.log)

**Comment by riederd** [comment]
Hi, unfortunately we had an electricity issue last night which affects the server on which the resource is located. The bad thing is that there is a holiday and long weekend now so it might take until Monday to get this fixed since not all things involved are in our hands. We are sorry for this.

**Comment by riederd** [comment]
The resource download should work again.

**Comment by antaralabiba97** [comment]
Ah great, will test the new run shortly, thank you. Will let you know if I encounter the same problems with MHCflurry (hopefully not!)

**Comment by antaralabiba97** [comment]
Hello,

So I tried running again with changing the CPUs to 8 for NeoFuse but unfortunately I encountered the same error as before. I have added the .nextflow.log , sample1_8_MHCFlurry.log and the sample1_MHCI_final.log. The sample1_8_NEK11_ALDH1L1_1_8.tsv does not exist in the location specficed in the error. Also, tried the singularity command again which you posted above and got the same output.

Not sure what is causing the issue with this missing file but please do let me know on ways to get this sorted.

Thank you!

[command.run.txt](https://github.com/icbi-lab/nextNEOpi/files/8791418/command.run.txt)
[sample1_8_MHCFlurry.log](https://github.com/icbi-lab/nextNEOpi/files/8791419/sample1_8_MHCFlurry.log)
[sample1_MHCI_final.log](https://github.com/icbi-lab/nextNEOpi/files/8791420/sample1_MHCI_final.log)
[nextflow.log](https://github.com/icbi-lab/nextNEOpi/files/8791421/nextflow.log)

**Comment by antaralabiba97** [comment]
Hello,

I was just wondering if you have had a chance to take a look at this error? Appreciate you may be busy but please let me know if there is any solution when you get the time! Thank you :)

**Comment by riederd** [comment]
Hi, we were out of office the last days. We continue to look into this and keep you updated.
Meanwhile, can you try to do the following:
```
$ cd /data/SBCS-BessantLab/Antara/nextNEOpi/work/30/21453b69c882f412b58dee6149538c
$ bash .command.run.sh
```

**Comment by antaralabiba97** [comment]
Hi, no worries and thank you.

Also, tried this but there is no ".command.run.sh" file. Below are the files available in the directory you specified.

<img width="1433" alt="Screenshot 2022-05-31 at 11 06 32" src="https://user-images.githubusercontent.com/80478944/171149381-d9a0a79d-eba1-4e68-823c-0c1579b92536.png">

**Comment by riederd** [comment]
sorry I meant `.command.run`

**Comment by antaralabiba97** [comment]
Hi, I ran the above and this is the error output...
<img width="1049" alt="Screenshot 2022-05-31 at 18 27 10" src="https://user-images.githubusercontent.com/80478944/171236564-cfeaaada-9e2a-4545-8a52-bc230a01ab6e.png">

**Comment by riederd** [comment]
Hi, it seems you are running into a resource limit. Can you post the output of:
```
$ ulimit -a
```
Can you do this on the head node of your cluster and on one of the compute nodes, in case you are running nextNEOpi on a cluster.

**Comment by antaralabiba97** [comment]
Hello, I am just running on the head node and not submitting a job on the cluster, this is the output on the head node. 


<img width="375" alt="Screenshot 2022-05-31 at 18 49 49" src="https://user-images.githubusercontent.com/80478944/171252361-b0023201-6c70-42fd-b396-0e58891c150f.png">

**Comment by riederd** [comment]
hmmm, this is stange, I do not see a big difference to our settings here. These two settings differ:
```
pending signals                 (-i) 12383285
max locked memory       (kbytes, -l) unlimited
```
But I don't think this is the problem.

What puzzles my also is that the `featureCounts` step takes so long in your case, more than 4 hrs. I would expect 10-20 min, as we see here in our environment.

Just to make sure if the `Resource temporarily unavailable` issue is really temporary can you please try once more to run 

```
$ cd /data/SBCS-BessantLab/Antara/nextNEOpi/work/30/21453b69c882f412b58dee6149538c
$ bash .command.run
```

Thanks

**Comment by antaralabiba97** [comment]
Hi, I ran again and now get the error below


<img width="1007" alt="Screenshot 2022-06-01 at 20 15 46" src="https://user-images.githubusercontent.com/80478944/171516833-6d76bdd1-b571-47e2-9013-400863f96c48.png">

**Comment by riederd** [comment]
So you really seem to hit some resource limit on your machine. Do you have many other processes running on that machine? Can you check with:
```
$ ps -eLf | wc -l
$ ps -eLf | grep hfy006 | wc -l
```
You can try to raise some limits:
```
$ ulimit -n 4096
$ ulimit -l unlimited
$ ulimit -u 8192
```
and then run the `.command.run` script again.

**Comment by antaralabiba97** [comment]
After doing the above running the ".command.run script" completed! I had to kill the previous processes which were still running from the nextflow run that exited with the MHCflurry error. Please let me know on how to proceed from the stage the pipeline exited. Thank you for all your help so far, glad to be one step closer! 

<img width="1474" alt="Screenshot 2022-06-02 at 21 24 07" src="https://user-images.githubusercontent.com/80478944/171732246-a4d7e5c8-2d66-48e8-8c93-defae3c3a205.png">

**Comment by riederd** [comment]
That's good! 
Now I suggest to do the following:
* create a file in the nextNEOpi `bin/` directory named `set_limits.sh` with the following content:
```
ulimit -n 4096
ulimit -u 8192
```
* Edit the `conf/process.config` file in the nexNEOpi directory and look for:
```
withName:Neofuse {
    container = 'https://apps-01.i-med.ac.at/images/singularity/NeoFuse_dev_0d1d4169.sif'
    cpus = 10
}
```
change it to:
```
withName:Neofuse {
    beforeScript = 'source /data/SBCS-BessantLab/Antara/nextNEOpi/bin/set_limits.sh'
    container = 'https://apps-01.i-med.ac.at/images/singularity/NeoFuse_dev_0d1d4169.sif'
    cpus = 10
}
```

* rerun the pipeline with the  `-resume` option set.

**Comment by antaralabiba97** [comment]
Hi, 

So I did all the above and the Neofuse part of the run completed and I have the output folder for this in my results! Thank for the help on this part, it's really appreciated!

However, I now have an error during the pVACseq stage which is causing the process to exit. I have attached the files associated with the error. 

[nextflow.log](https://github.com/icbi-lab/nextNEOpi/files/8837658/nextflow.log)
[command.run.txt](https://github.com/icbi-lab/nextNEOpi/files/8837659/command.run.txt)
[command.sh.txt](https://github.com/icbi-lab/nextNEOpi/files/8837661/command.sh.txt)




Feels like I'm nearly there so I am very excited for the run to complete and then hopefully once I have a working pipeline I will be able to run my other samples!

**Comment by riederd** [comment]
Hi, can you also try to reduce the number of CPUs to 10 for pVACseq?

For a manual test you may do this by editing `command.sh` in `/data/SBCS-BessantLab/Antara/nextNEOpi/work/09/7305b172968e7a9bc25e0b59f2eb8a` and set the threads parameter from `-t 40` to `-t 10`.
After this you may run:
```
$ cd /data/SBCS-BessantLab/Antara/nextNEOpi/work/09/7305b172968e7a9bc25e0b59f2eb8a
$ bash .command.run
```

if this works, you may change the `cpus` in `conf/process.config`

**Comment by antaralabiba97** [comment]
Hi, I tried doing the above, and the process aborts

<img width="587" alt="Screenshot 2022-06-07 at 13 07 09" src="https://user-images.githubusercontent.com/80478944/172375107-4156c73a-cb88-4c55-b5f3-46e2afe85e21.png">

**Comment by antaralabiba97** [comment]
The process exits with "Error: No command specified". 

<img width="1424" alt="Screenshot 2022-06-07 at 14 49 12" src="https://user-images.githubusercontent.com/80478944/172397926-a819c97b-46f3-46aa-88ae-980dd1abd0e2.png">

**Comment by riederd** [comment]
Hmmm, I think you hit an issue in pVACseq, which might be solved in the newest version. I'll prepare an updated image this evening. Meanwhile, can you send me a tar archive from that working directory, so that I can test locally. You would need to create it as follows:
```
$ cd /data/SBCS-BessantLab/Antara/nextNEOpi/work/09
$ tar -chvzf testdata.tar.gz 7305b172968e7a9bc25e0b59f2eb8a
```
Please send me a private e-mail with a download link for the resulting `testdata.tar.gz`.

**Comment by antaralabiba97** [comment]
Sent the email, please let me know if you do not receive it. Thank you.

**Comment by riederd** [comment]
One more thing to try:
```
$ cd /data/SBCS-BessantLab/Antara/nextNEOpi/work/09/7305b172968e7a9bc25e0b59f2eb8a
$ rm -rf ./MHC_Class*
$ singularity exec --no-mount hostfs -B /data/SBCS-BessantLab/Antara/nextNEOpi -B "$PWD" --no-home -B /data/SBCS-BessantLab/Antara/nextNEOpi/assets -B /data/SBCS-BessantLab/Antara/nextNEOpi/tmpDir -B /data/SBCS-BessantLab/Antara/nextNEOpi/resources -B /data/SBCS-BessantLab/Antara/nextNEOpi/resources/databases/iedb:/opt/iedb -B /data/SBCS-BessantLab/Antara/nextNEOpi/resources/databases/mhcflurry_data:/opt/mhcflurry_data /data/SBCS-BessantLab/Antara/nextNEOpi/work/singularity/apps-01.i-med.ac.at-images-singularity-pVACtools_3.0.0_icbi_5dfca363.sif /bin/bash
Singularity> bash .command.sh
```

**Comment by riederd** [comment]
...and in case you get an netMHCstab error please look for the following line in `.command.sh`:
```
--netmhc-stab
```
and remove it and re-run the commands above.
NetMHCstab is run from a webservice which is not always working as expected. It can be disabled in nextNEOpi with the option `--use_NetMHCstab false`

**Comment by antaralabiba97** [comment]
I didn't get the netMHCstab error but the same error as before "Error: No command specified". 

<img width="1455" alt="Screenshot 2022-06-08 at 18 56 45" src="https://user-images.githubusercontent.com/80478944/172684951-b105bb74-cb92-48b1-98e6-816a28b2552f.png">

**Comment by riederd** [comment]
Did you get pandas warnings with this?

**Comment by riederd** [comment]
This is interesting, you should not get those. Can you check the pandas version and path for me:
```
$ cd /data/SBCS-BessantLab/Antara/nextNEOpi/work/09/7305b172968e7a9bc25e0b59f2eb8a
$ rm -rf ./MHC_Class*
$ singularity exec --no-mount hostfs -B /data/SBCS-BessantLab/Antara/nextNEOpi -B "$PWD" --no-home -B /data/SBCS-BessantLab/Antara/nextNEOpi/assets -B /data/SBCS-BessantLab/Antara/nextNEOpi/tmpDir -B /data/SBCS-BessantLab/Antara/nextNEOpi/resources -B /data/SBCS-BessantLab/Antara/nextNEOpi/resources/databases/iedb:/opt/iedb -B /data/SBCS-BessantLab/Antara/nextNEOpi/resources/databases/mhcflurry_data:/opt/mhcflurry_data /data/SBCS-BessantLab/Antara/nextNEOpi/work/singularity/apps-01.i-med.ac.at-images-singularity-pVACtools_3.0.0_icbi_5dfca363.sif /bin/bash
Singularity> pip show pandas
```
and

```
Singularity> python
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
>>> print(pd.__version__)
```

Can you then try the new test image that I prepared:
```
$ cd /data/SBCS-BessantLab/Antara/nextNEOpi/work/09/7305b172968e7a9bc25e0b59f2eb8a
$ rm -rf ./MHC_Class*
$ singularity exec --no-mount hostfs -B /data/SBCS-BessantLab/Antara/nextNEOpi -B "$PWD" --no-home -B /data/SBCS-BessantLab/Antara/nextNEOpi/assets -B /data/SBCS-BessantLab/Antara/nextNEOpi/tmpDir -B /data/SBCS-BessantLab/Antara/nextNEOpi/resources -B /data/SBCS-BessantLab/Antara/nextNEOpi/resources/databases/iedb:/opt/iedb -B /data/SBCS-BessantLab/Antara/nextNEOpi/resources/databases/mhcflurry_data:/opt/mhcflurry_data https://apps-01.i-med.ac.at/images/singularity/pVACtools_3.0.1_icbi_test_20220609.sif /bin/bash
Singularity> pip show pandas
```
and then:
```
Singularity> bash .command.sh
```

**Comment by antaralabiba97** [comment]
Did all the steps to check python and pandas version which are the same as yours.

Tried the new test image and it worked!
<img width="1443" alt="Screenshot 2022-06-09 at 11 06 28" src="https://user-images.githubusercontent.com/80478944/172822497-a0628e58-498a-409e-9550-e602868ce784.png">

When I go and look in the folder with the outputs I don't see the "sample1_tumor.filtered.tsv" file but just the filtered results file for HLA-A*02:01 "sample1_tumor_HLA-A*02:01.filtered.tsv". 

<img width="1449" alt="Screenshot 2022-06-09 at 11 10 08" src="https://user-images.githubusercontent.com/80478944/172823580-13cc9913-bbec-4c5d-84b6-c4adae69fc91.png">





For now, I have not included "HLA-HD" in the pipeline so no MHC-II predictions are generated but once this run finishes completely I will go back to include it.

**Comment by riederd** [comment]
Cool. Thanks!

The final filtered result for the entire sample is generated by nextNEOpi after collecting the parallelized junks. So what you see is expected.

I did not disclose my pandas version ;-) so I don't think you can state that it is the same as yours. Would it be possible for you to post the output of:
```
$ cd /data/SBCS-BessantLab/Antara/nextNEOpi/work/09/7305b172968e7a9bc25e0b59f2eb8a
$ singularity exec --no-mount hostfs -B /data/SBCS-BessantLab/Antara/nextNEOpi -B "$PWD" --no-home -B /data/SBCS-BessantLab/Antara/nextNEOpi/assets -B /data/SBCS-BessantLab/Antara/nextNEOpi/tmpDir -B /data/SBCS-BessantLab/Antara/nextNEOpi/resources -B /data/SBCS-BessantLab/Antara/nextNEOpi/resources/databases/iedb:/opt/iedb -B /data/SBCS-BessantLab/Antara/nextNEOpi/resources/databases/mhcflurry_data:/opt/mhcflurry_data /data/SBCS-BessantLab/Antara/nextNEOpi/work/singularity/apps-01.i-med.ac.at-images-singularity-pVACtools_3.0.0_icbi_5dfca363.sif /bin/bash
Singularity> pip show pandas
```

**Comment by antaralabiba97** [comment]
Hmm, yes I understand just had a read around this.
This is the version:

<img width="1460" alt="Screenshot 2022-06-09 at 12 54 42" src="https://user-images.githubusercontent.com/80478944/172842248-6840883d-f86a-465f-adfe-1aa5bb8a83b2.png">

**Comment by riederd** [comment]
Thanks, I'll try to reproduce this

**Comment by riederd** [comment]
I think I get a clue what happens a your site. Can you please post the output of:
```
grep "bind path" /etc/singularity/singularity.conf
```

**Comment by antaralabiba97** [comment]
Here is the output for the above command:


<img width="1454" alt="Screenshot 2022-06-09 at 14 51 36" src="https://user-images.githubusercontent.com/80478944/172863621-4b17211e-10bc-4c56-9172-5ab139cc6746.png">

**Comment by riederd** [comment]
One thing, that may work would be to set a "fake home" in the `params.conf` which points to the `tmpDir`

e.g.
```
singularity {
    enabled = true
    autoMounts = true
    runOptions =  "--no-home" + " -H " + params.singularityTmpMount + " -B " +  params.singularityAssetsMount + " -B " + params.singularityTmpMount + " -B " + params.resourcesBaseDir + params.singularityHLAHDmount + " -B " + params.databases.IEDB_dir + ":/opt/iedb" + " -B " + params.databases.MHCFLURRY_dir + ":/opt/mhcflurry_data"
}
```
Might work, but this is untested, so I have no idea if other problems pop up with is hack.

**Comment by antaralabiba97** [comment]
After doing what you suggested above, the pVACseq process did start more than 48 hours ago 😅 but many processes have gone defunct straight after starting and the processes which are running have been running for a very long time. Think the best thing to do is to run it on my PC when it arrives as not sure how to overcome the issues with the cluster. 

<img width="311" alt="Screenshot 2022-06-12 at 22 15 56" src="https://user-images.githubusercontent.com/80478944/173333959-dda71ca4-1f22-47a4-84cf-00551869925b.png">
<img width="1503" alt="Screenshot 2022-06-13 at 11 17 08" src="https://user-images.githubusercontent.com/80478944/173334968-54060d64-0994-4fe3-b7b4-47d76a46d8c2.png">
