### ISSUE TITLE
Nextflow installation error

### ISSUE THREAD

**Issue by bbmorris1** [icbi-lab/nextNEOpi#51]
Hi, 

I'm attempting to install & run the nextNEOpi pipeline on my institution's HPC. 

I'm receiving the following error message: 

"$ nextflow run icbi-lab/nextNEOpi --help

N E X T F L O W  ~  version 22.10.8
Pulling icbi-lab/nextNEOpi ...
WARN: Cannot read project manifest -- Cause: Remote resource not found: https://api.github.com/repos/icbi-lab/nextNEOpi/contents/nextflow.config
Remote resource not found: https://api.github.com/repos/icbi-lab/nextNEOpi/contents/main.nf"

How do I address this? 

Thanks in advance!

**Comment by riederd** [comment]
Hi thanks for your interest in nextNEOpi.
You need to download the release package and unpack it locally and then run it from there according to the README

**Comment by bbmorris1** [comment]
Hi,

When attempting to install and run the nextNEO pipeline, I'm finding that a number of the required resources aren't included in the https://apps-01.i-med.ac.at/resources/nextneopi/nextNEOpi_1.4_resources.tar.gz bundle. 

Specifically, the GRCh38d1.vd1/fasta folder is missing (containing needed reference files GRCh38.d1.vd1.fa, GRCh38.d1.vd1.fa.fai, GRCh38.d1.vd1.dict, hg38.len, and chromosomes). Additionally, the GRCh38.d1.vd1/index/bwa/ folder is missing. 

I've also noticed that the databases/iedb, databases/mhcflurry_data, and databases/vep_cache are all empty following unpacking of the resource bundle.

For reference, the installation was done on a permissive server (i.e. no firewall restrictions) and did not time out. 

Is there a step that I am missing? Or an updated resources bundle that I should use? I've attempted to download & unpack the resources bundle twice now. At present, it looks like I have to pull all of these files in by hand.

**Comment by riederd** [comment]
Hi, thanks for your interest in `nextNEOpi`
The resources bundle includes all resources that are required. Maybe your download has failed.

`iedb`, `mhcflurry`, ans `vep` databases will be installed automatically during the first run of the pipeline and are not distributed via the resources bundle.
