### ISSUE TITLE
Target regions bed file for TESLA patients 4,8,9

### ISSUE THREAD

**Issue by mantczakaus** [icbi-lab/nextNEOpi#54]
Hi, 
I was wondering if you would be able to advise which bed file you used to process patients 4,8,9 from the TESLA dataset. The file provided in the dataset is not compatible with the GRCh38 that is used in the pipeline by default (some regions are out of bounds). The file says Agilent SureSelect DNA - Human All Exon v.2 Kit, it doesn't say which genome version it should be compatible with. It's not available on Agilent website anymore and it's difficult to find a file like on the Internet - I'm not sure which resources I could trust.
I would highly appreciate any help on this. I also contacted Agilent and Parker Institute where the TESLA project was run but I am still waiting for their responses.
Best wishes,
Magda

**Comment by riederd** [comment]
We just used the SureSelect v6 (which is provided by the pipeline). The regions get padded by `params.readLength + 100` in `nextNEOpi`. This should hopefully cover most of the captured parts.

**Comment by riederd** [comment]
As this is not an issue with the functionality of `nextNEOpi` I close it for now.

**Comment by mantczakaus** [comment]
thanks for your help!
