### ISSUE TITLE
nextNEO resources bundle installation issues

### ISSUE THREAD

**Issue by bbmorris1** [icbi-lab/nextNEOpi#58]
Hi,

When attempting to install and run the nextNEO pipeline, I'm finding that a number of the required resources aren't included in the https://apps-01.i-med.ac.at/resources/nextneopi/nextNEOpi_1.4_resources.tar.gz bundle.

Specifically, the GRCh38d1.vd1/fasta folder is missing (containing needed reference files GRCh38.d1.vd1.fa, GRCh38.d1.vd1.fa.fai, GRCh38.d1.vd1.dict, hg38.len, and chromosomes). Additionally, the GRCh38.d1.vd1/index/bwa/ folder is missing.

I've also noticed that the databases/iedb, databases/mhcflurry_data, and databases/vep_cache are all empty following unpacking of the resource bundle.

For reference, the installation was done on a permissive server (i.e. no firewall restrictions) and did not time out.

Is there a step that I am missing? Or an updated resources bundle that I should use? I've attempted to download & unpack the resources bundle twice now. At present, it looks like I have to pull all of these files in by hand.

**Comment by riederd** [comment]
Hi, thanks for your interest in nextNEOpi
The resources bundle includes all resources that are required. Maybe your download has failed.

iedb, mhcflurry, ans vep databases will be installed automatically during the first run of the pipeline and are not distributed via the resources bundle.

**Comment by bbmorris1** [comment]
Hi, I downloaded the resource bundle again at an off hour and got a more complete bundle! 

However, I'm still encountering two persistent errors during setup.

1) I'm running into a cryptic error when attempting to run nextNEOpi on the test data. 

Specifically, I'm getting the following: 

"WARN: Warning: VEP cache not installed, starting installation. This may take a while.
WARN: Warning: VEP plugins not installed, starting installation. This may take a while.

Missing 'fromPath' parameter."

Should I download all VEP resources manually and unpack them into the vep_cache folder (under /resourcesBaseDir/databases/)? 

Or is there another step that I am missing?

2) Attempts to pull the required singularity images do not appear to be working. 

When running the test data, I'm shown log lines indicating that there is an attempt to pull the images ("Pulling singularity image https://.../images/singularity...") but my NXF_SINGULARITY_CACHEDIR remains empty. 

Is there something else that I should be doing to remedy this?

Thanks for your patience.

**Comment by riederd** [comment]
Sorry for the late reply.

@1.
Do you still have the `.nextflow.log` file for this run?

If not, can you try to delete the install check files for vep:
```
rm [path to your nextneopi]/resources/databases/vep_cache/*.chck
```
And then try to rerun and if it fails again, post the `.nextflow.log`

@2.
Make sure your machine has a working internet connection, i.e. it should be able to download:

```
https://apps-01.i-med.ac.at/images/singularity/NeoFuse_dev_92712e07.sif`
and
https://apps-01.i-med.ac.at/images/singularity/pVACtools_4.0.1_icbi_4ae2625d.sif
and
https://apps-01.i-med.ac.at/images/singularity/nextNEOpi_1.4.0_f894e892.sif
and
https://apps-01.i-med.ac.at/images/singularity/rigscore_1.4_b0be2896.sif
```

**Comment by riederd** [comment]
No feedback, assume it is solved
