### ISSUE TITLE
Failed to run, issues related to pvacseq , etc

### ISSUE THREAD

**Issue by CSree** [icbi-lab/nextNEOpi#59]
Hi, I ran the pipeline on 3 samples, two of them ended with identical slurm outputs as attached below. 

<img width="861" alt="Screenshot 2023-10-27 at 1 52 27 PM" src="https://github.com/icbi-lab/nextNEOpi/assets/67707774/93d283df-1a89-407d-a3aa-a903f77bb878">

The third generated results only in the Fusions folder, but not the epitopes for Class I and Class II. The end of the slurm output is below

<img width="652" alt="Screenshot 2023-10-27 at 1 46 12 PM" src="https://github.com/icbi-lab/nextNEOpi/assets/67707774/d1d0021d-c059-4dfd-bdec-3f2232fa51a5">

The pic below shows the output files of a successful run by my senior colleague a few months ago, that generated filtered and unfiltered epitopes, along with neoFuse related files, for the sample on the left. However for the third sample I that ran [sample 27], the pic on the right shows only the Fusions folder has the output files. The csv file with tumor mutation burden stats is also not generated.

<img width="911" alt="Screenshot 2023-10-27 at 2 06 01 PM" src="https://github.com/icbi-lab/nextNEOpi/assets/67707774/3f3ee5c6-f382-4e9b-b6b1-49a7e65bd78f">

- Is this something to do with the pvacseq tool ?
- How to detect if the input fastq.gz files were faulty, since the pipeline has run successfully earlier on many samples earlier..

Thanks so much,
Chaitra
[junior Bioinformatician, NYU Langone]

**Comment by mantczakaus** [comment]
Hi, I've been having the same issue. I've reported a bug to pvactools https://github.com/griffithlab/pVACtools/issues/1035 - Magda

**Comment by riederd** [comment]
The first error you get from `Sample26` is an issue with the `NetMHCStabPan` server which is not under our control, if it is permanent you may use the `--use_NetMHCstab False` option to disable `NetMHCstab`.

For your `Sample27` I'd need the `.nextflow.log` log file to get an idea what might be the cause for the missing files (screenshots are not very helpful).

Are there any results in `results/analyses/sample1/04_variations` ? Can you check with:
`ls -lR results/analyses/sample1/04_variations`

**Comment by CSree** [comment]
Thank you for your prompt responses. Please find attached the nextflow log file, and the list of variations detected.
To see if there are sample issues, I am running the pipeline on a sample on which it ran successfully a few months ago, and I will compare the files generated.
Please share any other steps I could take.
Thanks
[Nextflow_log.txt](https://github.com/icbi-lab/nextNEOpi/files/13221107/Nextflow_log.txt)
[variations.txt](https://github.com/icbi-lab/nextNEOpi/files/13221109/variations.txt)

**Comment by riederd** [comment]
Hi, sorry for the late rply

can you also post the following file `/gpfs/scratch/cs5359/Projects/Krogsgaardlab/NeoAg/pipeline/Sample27/work/4a/074d749005cea15578a2ed709eb2da/.command.run`

**Comment by riederd** [comment]
No feedback, assuming it as solved
