### ISSUE TITLE
including SNV/indel calling on RNA-seq data

### ISSUE THREAD

**Issue by zktuong** [icbi-lab/nextNEOpi#61]
hi, was wondering if the RNA-seq SNV variant calling for RNA-seq data is performed during the pipeline? If not, can this be added into future version?

https://gatk.broadinstitute.org/hc/en-us/articles/360035531192-RNAseq-short-variant-discovery-SNPs-Indels-

**Comment by riederd** [comment]
Hi,
thanks for the suggestion, however, the proposed GATK pipeline/workflow is not suitatable to call somatic mutations, it would also call any germline mutation which are not necessarily specific to the tumor, which in turn would produce antigen predictions which are not specific to the tumor.
