### ISSUE TITLE
HLA-HD silently fails if bowtie2 is not installed/loaded

### ISSUE THREAD

**Issue by dmgie** [icbi-lab/nextNEOpi#62]
Hi, 

I had recently been able to run the nextNEOpi pipeline through (after some minor modification). When looking at the results section I noticed that the `./results/neoantigens/[sample]/Class_II` folders were empty. 

At first I thought that HLA-HD wasn't found, but in Nextflow's output I see the line
`Found /data/HLA-HD/hlahd.1.7.0/bin/hlahd.sh at: /data/HLA-HD/hlahd.1.7.0/bin/hlahd.sh`, so at least the HLA-HD is being found.

I additionally checked `./results/analyses/[sample]/10_HLA_typing/HLA_HD/`, but theres only one file which just has `Not typed` for all of them.

Lastly, I checked the actual `work/*` folder for the HLA-HD process, and found out that in `.command.err` it wasn't able to fully run at all:
```
/data/HLA-HD/hlahd.1.7.0/bin/hlahd.sh: line 101: bowtie2: command not found
/data/HLA-HD/hlahd.1.7.0/bin/hlahd.sh: line 102: bowtie2: command not found
/data/HLA-HD/hlahd.1.7.0/bin/hlahd.sh: line 103: bowtie2: command not found
/data/HLA-HD/hlahd.1.7.0/bin/hlahd.sh: line 104: bowtie2: command not found
rm: cannot remove './sample1_tumor_DNA/mapfile/sample1_tumor_DNA.all_exon.R1.D.sam': No such file or directory
rm: cannot remove './sample1_tumor_DNA/mapfile/sample1_tumor_DNA.all_exon.R2.D.sam': No such file or directory
rm: cannot remove './sample1_tumor_DNA/mapfile/sample1_tumor_DNA.all_intron.R1.D.sam': No such file or directory
rm: cannot remove './sample1_tumor_DNA/mapfile/sample1_tumor_DNA.all_intron.R2.D.sam': No such file or directory
/data/HLA-HD/hlahd.1.7.0/bin/hlahd.sh: line 132: bowtie2: command not found
/data/HLA-HD/hlahd.1.7.0/bin/hlahd.sh: line 133: bowtie2: command not found
mv: cannot stat './sample1_tumor_DNA/mapfile/sample1_tumor_DNA.fastq': No such file or directory
mv: cannot stat './sample1_tumor_DNA/mapfile/sample1_tumor_DNA.fastq': No such file or directory
rm: cannot remove './sample1_tumor_DNA/mapfile/sample1_tumor_DNA_all.R1.sam': No such file or directory
rm: cannot remove './sample1_tumor_DNA/mapfile/sample1_tumor_DNA_all.R2.sam': No such file or directory
rm: cannot remove './sample1_tumor_DNA/mapfile/sample1_tumor_DNA.exon.over.R1.fastq': No such file or directory
rm: cannot remove './sample1_tumor_DNA/mapfile/sample1_tumor_DNA.exon.over.R2.fastq': No such file or directory
/data/HLA-HD/hlahd.1.7.0/bin/hlahd.sh: line 150: bowtie2: command not found
/data/HLA-HD/hlahd.1.7.0/bin/hlahd.sh: line 151: bowtie2: command not found
/data/HLA-HD/hlahd.1.7.0/bin/hlahd.sh: line 158: bowtie2: command not found
/data/HLA-HD/hlahd.1.7.0/bin/hlahd.sh: line 159: bowtie2: command not found
/data/HLA-HD/hlahd.1.7.0/bin/hlahd.sh: line 182: bowtie2: command not found
/data/HLA-HD/hlahd.1.7.0/bin/hlahd.sh: line 183: bowtie2: command not found
/data/HLA-HD/hlahd.1.7.0/bin/hlahd.sh: line 184: bowtie2: command not found
/data/HLA-HD/hlahd.1.7.0/bin/hlahd.sh: line 185: bowtie2: command not found
/data/HLA-HD/hlahd.1.7.0/bin/hlahd.sh: line 208: bowtie2: command not found
/data/HLA-HD/hlahd.1.7.0/bin/hlahd.sh: line 209: bowtie2: command not found
/data/HLA-HD/hlahd.1.7.0/bin/hlahd.sh: line 210: bowtie2: command not found
/data/HLA-HD/hlahd.1.7.0/bin/hlahd.sh: line 211: bowtie2: command not found
rm: cannot remove './sample1_tumor_DNA/mapfile/sample1_tumor_DNA.all_intron.R1.sam': No such file or directory
rm: cannot remove './sample1_tumor_DNA/mapfile/sample1_tumor_DNA.all_intron.R2.sam': No such file or directory
```

As I did not have `bowtie2` installed on the HPC cluster, HLA-HD wasn't able to run, but still gave an exit code of 0, meaning it was "successful" and Nextflow continued on.

Would pulling a singularity image for bowtie2 (i.e https://hub.docker.com/r/staphb/bowtie2/ or https://hub.docker.com/r/biocontainers/bowtie2/) in [this process](https://github.com/icbi-lab/nextNEOpi/blob/fe7b21cdc0b97aae38195e5f5ac1b9851674f6b1/nextNEOpi.nf#L4990) be a possible solution? Or possibly an error in case there is a missing bowtie2 installation?

(On another note: I had a collected a list of issues that I had run into i.e VepTab, CNNScoreVariants as well as some of the others mainly related to resources; would it be of any help to post/list them somewhere (in an Issue / Wiki Page / PR) in case people encounter similar issues?)

**Comment by riederd** [comment]
Hi,
if you need to run `HLA-HD` you will also need to provide `bowtie2` which needs to be accessible via `$PATH`.

Thanks for letting us know that `HLA-HD` still exits with `0` in the case `bowtie2` is not found. I'll add a check logic for that case and throw an error at start time if `bowtie2` is not in `$PATH`.
I'm not sure if pulling a container is the best solution, because if someone wants to run `HLA-HD` independent of `nextNEOpi` she/he will have to provide `bowtie2` anyways.

Feel free to post/list your findings/issues with the resources, we would be very happy to implement fixes or instructions.
