### ISSUE TITLE
Error executing process "installVEPcache"

### ISSUE THREAD

**Issue by ryao-mdanderson** [icbi-lab/nextNEOpi#63]
Dear nextNEOpi authors:

After rounds of singularity images pull failures, I put singularity images in /risapps/singularity/repo/nextneopi/1.4.0, with the following images

apps-01.i-med.ac.at-images-singularity-NeoFuse_dev_92712e07.sif.pulling.1700070865761
apps-01.i-med.ac.at-images-singularity-nextNEOpi_1.4.0_f894e892.sif
depot.galaxyproject.org-singularity-ensembl-vep-110.0--pl5321h2a3209d_0.img
depot.galaxyproject.org-singularity-fastqc-0.12.1--hdfd78af_0.img
depot.galaxyproject.org-singularity-gatk-3.8--hdfd78af_11.img.pulling.1700070238115
depot.galaxyproject.org-singularity-manta-1.6.0--h9ee0642_1.img
depot.galaxyproject.org-singularity-multiqc-1.14--pyhdfd78af_0.img
depot.galaxyproject.org-singularity-multiqc-1.14--pyhdfd78af_0.img.pulling.1700070222434
depot.galaxyproject.org-singularity-strelka-2.9.10--h9ee0642_1.img

Then set up variable
export NXF_SINGULARITY_CACHEDIR="/risapps/singularity/repo/nextneopi/1.4.0"

I attempted to run command
$ nextflow run nextNEOpi.nf --batchFile testdata_batchFile_FASTQ.csv --CNVkit false -profile singularity -config conf/params.config --accept_license
  
-- outputs
 see lots of process
 ...
 also see the following message
 Error executing process > 'installVEPcache (installVEPcache)'

Caused by:
  Process `installVEPcache (installVEPcache)` terminated with an error exit status (110)

Command executed:

  mkdir -p /rsrch3/home/itops/ryao/nextNEOpi/reference/nextneopi-1.4.0//databases/vep_cache
  vep_install \
      -a cf \
      -s homo_sapiens \
      -y GRCh38 \
      -c /rsrch3/home/itops/ryao/nextNEOpi/reference/nextneopi-1.4.0//databases/vep_cache \
      --CACHE_VERSION 110 \
      --CONVERT 2> vep_errors.txt && \
  echo "OK" > .homo_sapiens_GRCh38_110_cache_ok.chck && \
  cp -f  .homo_sapiens_GRCh38_110_cache_ok.chck /rsrch3/home/itops/ryao/nextNEOpi/reference/nextneopi-1.4.0/databases/vep_cache/.homo_sapiens_GRCh38_110_cache_oexecutor >  local (104)

 [icbi/nextNEOpi] Pipeline Complete! You can find your results in /rsrch3/home/itops/ryao/nextNEOpi/results
  ...

I did see outputs in /rsrch3/home/itops/ryao/nextNEOpi/results
But I don't know how to fix vep_install error message.

Thank you for your suggestion.
Rong Yao

**Comment by riederd** [comment]
Can you post the log file `.nextflow.log`

**Comment by ryao-mdanderson** [comment]
[nextflow.log](https://github.com/icbi-lab/nextNEOpi/files/13379530/nextflow.log)
Hi @riederd Please see my attached nextflow.log file. Thank you.

**Comment by riederd** [comment]
And now I'd need 
```
/rsrch3/home/itops/ryao/nextNEOpi/work/05/de5b175ee91ee21cd64c8f7cf9646e/.command.run
/rsrch3/home/itops/ryao/nextNEOpi/work/05/de5b175ee91ee21cd64c8f7cf9646e/.command.err
/rsrch3/home/itops/ryao/nextNEOpi/work/05/de5b175ee91ee21cd64c8f7cf9646e/.command.log
/rsrch3/home/itops/ryao/nextNEOpi/work/05/de5b175ee91ee21cd64c8f7cf9646e/.command.out
/rsrch3/home/itops/ryao/nextNEOpi/work/05/de5b175ee91ee21cd64c8f7cf9646e/vep_errors.txt
````

Thanks

**Comment by ryao-mdanderson** [comment]
[vep_errors.txt](https://github.com/icbi-lab/nextNEOpi/files/13380216/vep_errors.txt)
[command.out.txt](https://github.com/icbi-lab/nextNEOpi/files/13380217/command.out.txt)
[command.log](https://github.com/icbi-lab/nextNEOpi/files/13380218/command.log)
[command.err.txt](https://github.com/icbi-lab/nextNEOpi/files/13380219/command.err.txt)
[command.run.txt](https://github.com/icbi-lab/nextNEOpi/files/13380220/command.run.txt)

Here are they - I put postfix .txt in order to allow upload. Thanks!

**Comment by riederd** [comment]
Hi, looking at the `vep_errors.txt` it seems your system has connection issues:

```
ERROR: Could not connect to FTP host ftp.ensembl.org
Connection timed out
```
Please make sure that  your system can connect to *ftp.ensembl.org* in order to download the cache files.

**Comment by ryao-mdanderson** [comment]
Thank you for pointing out. I will try and update with you.

**Comment by riederd** [comment]
No feedback, assuming the issue as solved
