### ISSUE TITLE
`pVACseq ` terminated with an error exit status (1) 

### ISSUE THREAD

**Issue by sasi-arunachalam** [icbi-lab/nextNEOpi#66]
Dear author,
  Thank you for the nice pipeline. I  recently ran nextNEOpi pipeline on one sample( DNA tumor, DNA normal and RNA tumor).
The pipeline produced all expected five folders. However, in analysis folder 4 subfolders (pVACseq,mixMHC2pred,CSIN,IGS,BCR_TCR)) were missing. 

A)**I have attached the screen shot of overall run** 
![Screenshot 2023-11-27 at 7 31 56 PM](https://github.com/icbi-lab/nextNEOpi/assets/33466870/256de3bf-b4ec-4e22-b2d5-e909dd67ea62)

B) I believe the error is ValueError: Input X contains NaN.

**Below is the copy paste of actual error** 

Error executing process > 'pVACseq (10-TM-FreshFrozen)'

Caused by:
  Process `pVACseq (10-TM-FreshFrozen)` terminated with an error exit status (1)

Command executed:

  pvacseq run \
      --iedb-install-directory /opt/iedb \
      -t 10 \
      -p 10-TM-FreshFrozen_vep_phased.vcf.gz \
      -e1 8,9,10,11 \
      -e2 15,16,17,18,19,20,21,22,23,24,25 \
      --normal-sample-name 10-TM-FreshFrozen_normal \
      --tumor-purity 1 \
       \
      --netmhc-stab \
      --binding-threshold 500 --top-score-metric median --minimum-fold-change 0.0 --normal-cov 5 --tdna-cov 10 --trna-cov 10 --normal-vaf 0.02 --tdna-vaf 0.25 --trna-vaf 0.25 --expn-val 1 --maximum-transcript-support-level 1 \
      10-TM-FreshFrozen_vep_somatic_gx.vcf.gz 10-TM-FreshFrozen_tumor HLA-B*18:01 NetMHCpan NetMHCpanEL MHCflurry MHCflurryEL NetMHCIIpan NetMHCIIpanEL ./
  
  if [ -e ./MHC_Class_I/10-TM-FreshFrozen_tumor.filtered.tsv ]; then
      mv ./MHC_Class_I/10-TM-FreshFrozen_tumor.filtered.tsv ./MHC_Class_I/10-TM-FreshFrozen_tumor_HLA-B*18:01.filtered.tsv
  fi
  if [ -e ./MHC_Class_I/10-TM-FreshFrozen_tumor.all_epitopes.tsv ]; then
      mv ./MHC_Class_I/10-TM-FreshFrozen_tumor.all_epitopes.tsv ./MHC_Class_I/10-TM-FreshFrozen_tumor_HLA-B*18:01.all_epitopes.tsv
  fi
  if [ -e ./MHC_Class_II/10-TM-FreshFrozen_tumor.filtered.tsv ]; then
      mv ./MHC_Class_II/10-TM-FreshFrozen_tumor.filtered.tsv ./MHC_Class_II/10-TM-FreshFrozen_tumor_HLA-B*18:01.filtered.tsv
  fi
  if [ -e ./MHC_Class_II/10-TM-FreshFrozen_tumor.all_epitopes.tsv ]; then
      mv ./MHC_Class_II/10-TM-FreshFrozen_tumor.all_epitopes.tsv ./MHC_Class_II/10-TM-FreshFrozen_tumor_HLA-B*18:01.all_epitopes.tsv
  fi

Command exit status:
  1

Command output:
  Making binding predictions on Allele HLA-B*18:01 and Epitope Length 8 with Method NetMHCpanEL - File MHC_Class_I/tmp/10-TM-FreshFrozen_tumor.netmhcpan_el.HLA-B*18:01.8.tsv_201-242 - Completed
  Making binding predictions on Allele HLA-B*18:01 and Epitope Length 9 with Method MHCflurry - File MHC_Class_I/tmp/10-TM-FreshFrozen_tumor.MHCflurry.HLA-B*18:01.9.tsv_201-242
  Making binding predic10.tsv_201-242
  Making binding predictions on Allele HLA-B*18:01 and Epitope Length 10 with Method NetMHCpanEL - File MHC_Class_I/tmp/10-TM-FreshFrozen_tumor.netmhcpan_el.HLA-B*18:01.10.tsv_201-242
  Making binding predictions on Allele HLA-B*18:01 and Epitope Length 8 with Method MHCflurry - File MHC_Class_I/tmp/10-TM-FreshFrozen_tumor.MHCflurry.HLA-B*18:01.8.tsv_1-200
  Making binding predictions on Allele HLA-B*18:01 and Epitope Length 11 with Method NetMHCpan - File MHC_Class_I/tmp/10-TM-FreshFrozen_tumor.netmhcpan.HLA-B*18:01.11.tsv_201-242
  Making binding predictions on Allele HLA-B*18:01 and Epitope Length 9 with Method NetMHCpan - File MHC_Class_I/tmp/10-TM-FreshFrozen_tumor.netmhcpan.HLA-B*18:01.9.tsv_201-242 - Completed
  Making binding predictions on Allele HLA-B*18:01 and Epitope Length 9 with Method NetMHCpanEL - File MHC_Class_I/tmp/10-TM-FreshFrozen_tumor.netmhcpan_el.HLA-B*18:01.9.tsv_201-242
  Making binding predictions on Allele HLA-B*18:01 and Epitope Length 8 with Method NetMHCpanEL - File MHC_Class_I/tmp/10-TM-FreshFrozen_tumor.netmhcpan_el.HLA-B*18:01.8.tsv_201-242 - Completed
  Making binding predictions on Allele HLA-B*18:01 and Epitope Length 9 with Method MHCflurry - File MHC_Class_I/tmp/10-TM-FreshFrozen_tumor.MHCflurry.HLA-B*18:01.9.tsv_201-242
  Making binding predictions on Allele HLA-B*18:01 and Epitope Length 10 with Method NetMHCpanEL - File MHC_Class_I/tmp/10-TM-FreshFrozen_tumor.netmhcpan_el.HLA-B*18:01.10.tsv_201-242 - Completed
  Making binding predictions on Allele HLA-B*18:01 and Epitope Length 11 with Method MHCflurry - File MHC_Class_I/tmp/10-TM-FreshFrozen_tumor.MHCflurry.HLA-B*18:01.11.tsv_201-242
  Making binding predictions on Allele HLA-B*18:01 and Epitope Length 9 with Method NetMHCpanEL - File MHC_Class_I/tmp/10-TM-FreshFrozen_tumor.netmhcpan_el.HLA-B*18:01.9.tsv_201-242 - Completed
  Making binding predictions on Allele HLA-B*18:01 and Epitope Length 11 with Method NetMHCpan - File MHC_Class_I/tmp/10-TM-FreshFrozen_tumor.netmhcpan.HLA-B*18:01.11.tsv_201-242 - Completed
  Making binding predictions on Allele HLA-B*18:01 and Epitope Length 11 with Method NetMHCpanEL - File MHC_Class_I/tmp/10-TM-FreshFrozen_tumor.netmhcpan_el.HLA-B*18:01.11.tsv_201-242
  Forcing tensorflow backend.
  Making binding predictions on Allele HLA-B*18:01 and Epitope Length 8 with Method MHCflurry - File MHC_Class_I/tmp/10-TM-FreshFrozen_tumor.MHCflurry.HLA-B*18:01.8.tsv_201-242 - Completed
  Making binding predictions on Allele HLA-B*18:01 and Epitope Length 8 with Method NetMHCpan - File MHC_Class_I/tmp/10-TM-FreshFrozen_tumor.netmhcpan.HLA-B*18:01.8.tsv_201-242
  Forcing tensorflow backend.
  Making binding predictions on Allele HLA-B*18:01 and Epitope Length 10 with Method MHCflurry - File MHC_Class_I/tmp/10-TM-FreshFrozen_tumor.MHCflurry.HLA-B*18:01.10.tsv_201-242 - Completed
  Making binding predictions on Allele HLA-B*18:01 and Epitope Length 10 with Method NetMHCpan - File MHC_Class_I/tmp/10-TM-FreshFrozen_tumor.netmhcpan.HLA-B*18:01.10.tsv_201-242
  Forcing tensorflow backend.
  Making binding predictions on Allele HLA-B*18:01 and Epitope Length 8 with Method MHCflurry - File MHC_Class_I/tmp/10-TM-FreshFrozen_tumor.MHCflurry.HLA-B*18:01.8.tsv_1-200 - Completed
  Making binding predictions on Allele HLA-B*18:01 and Epitope Length 8 with Method NetMHCpan - File MHC_Class_I/tmp/10-TM-FreshFrozen_tumor.netmhcpan.HLA-B*18:01.8.tsv_1-200
  Forcing tensorflow backend.
  Making binding predictions on Allele HLA-B*18:01 and Epitope Length 11 with Method MHCflurry - File MHC_Class_I/tmp/10-TM-FreshFrozen_tumor.MHCflurry.HLA-B*18:01.11.tsv_1-200 - Completed
  Making binding predictions on Allele HLA-B*18:01 and Epitope Length 11 with Method NetMHCpan - File MHC_Class_I/tmp/10-TM-FreshFrozen_tumor.netmhcpan.HLA-B*18:01.11.tsv_1-200
  Forcing tensorflow backend.
  Making binding predictions on Allele HLA-B*18:01 and Epitope Length 10 with Method MHCflurry - File MHC_Class_I/tmp/10-TM-FreshFrozen_tumor.MHCflurry.HLA-B*18:01.10.tsv_1-200 - Completed
  Making binding predictions on Allele HLA-B*18:01 and Epitope Length 10 with Method NetMHCpan - File MHC_Class_I/tmp/10-TM-FreshFrozen_tumor.netmhcpan.HLA-B*18:01.10.tsv_1-200
  Forcing tensorflow backend.
  Making binding predictions on Allele HLA-B*18:01 and Epitope Length 9 with Method MHCflurry - File MHC_Class_I/tmp/10-TM-FreshFrozen_tumor.MHCflurry.HLA-B*18:01.9.tsv_1-200 - Completed
  Making binding predictions on Allele HLA-B*18:01 and Epitope Length 9 with Method NetMHCpan - File MHC_Class_I/tmp/10-TM-FreshFrozen_tumor.netmhcpan.HLA-B*18:01.9.tsv_1-200
  Making binding predictions on Allele HLA-B*18:01 and Epitope Length 11 with Method NetMHCpanEL - File MHC_Class_I/tmp/10-TM-FreshFrozen_tumor.netmhcpan_el.HLA-B*18:01.11.tsv_201-242 - Completed
  Forcing tensorflow backend.
  Making binding predictions on Allele HLA-B*18:01 and Epitope Length 9 with Method MHCflurry - File MHC_Class_I/tmp/10-TM-FreshFrozen_tumor.MHCflurry.HLA-B*18:01.9.tsv_201-242 - Completed
  Making binding predictions on Allele HLA-B*18:01 and Epitope Length 8 with Method NetMHCpan - File MHC_Class_I/tmp/10-TM-FreshFrozen_tumor.netmhcpan.HLA-B*18:01.8.tsv_201-242 - Completed
  Making binding predictions on Allele HLA-B*18:01 and Epitope Length 10 with Method NetMHCpan - File MHC_Class_I/tmp/10-TM-FreshFrozen_tumor.netmhcpan.HLA-B*18:01.10.tsv_201-242 - Completed
  Making binding predictions on Allele HLA-B*18:01 and Epitope Length 9 with Method NetMHCpan - File MHC_Class_I/tmp/10-TM-FreshFrozen_tumor.netmhcpan.HLA-B*18:01.9.tsv_1-200 - Completed
  Making binding predictions on Allele HLA-B*18:01 and Epitope Length 9 with Method NetMHCpanEL - File MHC_Class_I/tmp/10-TM-FreshFrozen_tumor.netmhcpan_el.HLA-B*18:01.9.tsv_1-200
  Making binding predictions on Allele HLA-B*18:01 and Epitope Length 8 with Method NetMHCpan - File MHC_Class_I/tmp/10-TM-FreshFrozen_tumor.netmhcpan.HLA-B*18:01.8.tsv_1-200 - Completed
  Making binding predictions on Allele HLA-B*18:01 and Epitope Length 8 with Method NetMHCpanEL - File MHC_Class_I/tmp/10-TM-FreshFrozen_tumor.netmhcpan_el.HLA-B*18:01.8.tsv_1-200
  Making binding predictions on Allele HLA-B*18:01 and Epitope Length 10 with Method NetMHCpan - File MHC_Class_I/tmp/10-TM-FreshFrozen_tumor.netmhcpan.HLA-B*18:01.10.tsv_1-200 - Completed
  Making binding predictions on Allele HLA-B*18:01 and Epitope Length 10 with Method NetMHCpanEL - File MHC_Class_I/tmp/10-TM-FreshFrozen_tumor.netmhcpan_el.HLA-B*18:01.10.tsv_1-200
  Making binding predictions on Allele HLA-B*18:01 and Epitope Length 9 with Method NetMHCpanEL - File MHC_Class_I/tmp/10-TM-FreshFrozen_tumor.netmhcpan_el.HLA-B*18:01.9.tsv_1-200 - Completed
  Making binding predictions on Allele HLA-B*18:01 and Epitope Length 11 with Method NetMHCpan - File MHC_Class_I/tmp/10-TM-FreshFrozen_tumor.netmhcpan.HLA-B*18:01.11.tsv_1-200 - Completed
  Making binding predictions on Allele HLA-B*18:01 and Epitope Length 11 with Method NetMHCpanEL - File MHC_Class_I/tmp/10-TM-FreshFrozen_tumor.netmhcpan_el.HLA-B*18:01.11.tsv_1-200
  Making binding predictions on Allele HLA-B*18:01 and Epitope Length 8 with Method NetMHCpanEL - File MHC_Class_I/tmp/10-TM-FreshFrozen_tumor.netmhcpan_el.HLA-B*18:01.8.tsv_1-200 - Completed
  Making binding predictions on Allele HLA-B*18:01 and Epitope Length 10 with Method NetMHCpanEL - File MHC_Class_I/tmp/10-TM-FreshFrozen_tumor.netmhcpan_el.HLA-B*18:01.10.tsv_1-200 - Completed
  Making binding predictions on Allele HLA-B*18:01 and Epitope Length 11 with Method NetMHCpanEL - File MHC_Class_I/tmp/10-TM-FreshFrozen_tumor.netmhcpan_el.HLA-B*18:01.11.tsv_1-200 - Completed

Command error:
  /opt/conda/lib/python3.8/site-packages/keras/src/engine/training_v1.py:2359: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
    updates=self.state_updates,
  WARNING:tensorflow:From /opt/conda/lib/python3.8/site-packages/tensorflow/python/ops/init_ops.py:94: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
  Instructions for updating:
  Call initializer instance with the dtype argument instead of passing it to the constructor
  WARNING:tensorflow:From /opt/conda/lib/python3.8/site-packages/tensorflow/python/ops/init_ops.py:94: calling Zeros.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
  Instructions for updating:
  Call initializer instance with the dtype argument instead of passing it to the constructor
  /opt/conda/lib/python3.8/site-packages/keras/src/engine/training_v1.py:2359: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
    updates=self.state_updates,
  /opt/conda/lib/python3.8/site-packages/keras/src/engine/training_v1.py:2359: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
    updates=self.state_updates,
  /opt/conda/lib/python3.8/site-packages/keras/src/engine/training_v1.py:2359: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
    updates=self.state_updates,
  /opt/conda/lib/python3.8/site-packages/keras/src/engine/training_v1.py:2359: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
    updates=self.state_updates,
  /opt/conda/lib/python3.8/site-packages/keras/src/engine/training_v1.py:2359: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
    updates=self.state_updates,
  /opt/conda/lib/python3.8/site-packages/keras/src/engine/training_v1.py:2359: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
    updates=self.state_updates,
  /opt/conda/lib/python3.8/site-packages/keras/src/engine/training_v1.py:2359: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
    updates=self.state_updates,
  /opt/conda/lib/python3.8/site-packages/keras/src/engine/training_v1.py:2359: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
    updates=self.state_updates,
  WARNING:tensorflow:From /opt/conda/lib/python3.8/site-packages/tensorflow/python/ops/init_ops.py:94: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
  Instructions for updating:
  Call initializer instance with the dtype argument instead of passing it to the constructor
  WARNING:tensorflow:From /opt/conda/lib/python3.8/site-packages/tensorflow/python/ops/init_ops.py:94: calling Zeros.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
  Instructions for updating:
  Call initializer instance with the dtype argument instead of passing it to the constructor
  /opt/conda/lib/python3.8/site-packages/keras/src/engine/training_v1.py:2359: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
    updates=self.state_updates,
  CRITICAL:pymp:An exception occured in thread 8: (<class 'ValueError'>, Input X contains NaN.
  LogisticRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values).
  Traceback (most recent call last):
    File "/opt/conda/bin/pvacseq", line 8, in <module>
      sys.exit(main())
    File "/opt/conda/lib/python3.8/site-packages/pvactools/tools/pvacseq/main.py", line 123, in main
      args[0].func.main(args[1])
    File "/opt/conda/lib/python3.8/site-packages/pvactools/tools/pvacseq/run.py", line 138, in main
      pipeline.execute()
    File "/opt/conda/lib/python3.8/site-packages/pvactools/lib/pipeline.py", line 451, in execute
      self.call_iedb(chunks)
    File "/opt/conda/lib/python3.8/site-packages/pvactools/lib/pipeline.py", line 357, in call_iedb
      p.print("Making binding predictions on Allele %s and Epitope Length %s with Method %s - File %s - Completed" % (a, epl, method, filename))
    File "/opt/conda/lib/python3.8/site-packages/pymp/__init__.py", line 148, in __exit__
      raise exc_t(exc_val)
  ValueError: Input X contains NaN.
  LogisticRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values
  INFO:    Cleaning up image...

Work dir:
  /home/ubuntu/epitope/work_normal/64/dfceaa8042580a81220fa7d392d531

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

**Comment by sasi-arunachalam** [comment]
(singularity) ubuntu@ip-172-31-6-189:~/epitope/work_normal/64/dfceaa8042580a81220fa7d392d531$ bash .command.run

INFO:    Converting SIF file to temporary sandbox...
Executing MHC Class I predictions
Converting .vcf to TSV
TSV file already exists. Skipping.
Converting VCF to TSV
Warning: Proximal variant is not a missense mutation and will be skipped: chr2 140700416
Warning: Proximal variant is not a missense mutation and will be skipped: chr12 120641069
Warning: Proximal variant is not a missense mutation and will be skipped: chr20 5302730
Completed
Generating Variant Peptide FASTA and Key File
Completed
Parsing the Variant Peptide FASTA and Key File
Completed
Calculating Manufacturability Metrics
Completed
Splitting TSV into smaller chunks
Splitting TSV into smaller chunks - Entries 1-100
Split TSV file for Entries 1-100 already exists. Skipping.
Splitting TSV into smaller chunks - Entries 101-121
Split TSV file for Entries 101-121 already exists. Skipping.
Completed
Generating Variant Peptide FASTA and Key Files
Split FASTA file for Epitope Length 8 - Entries 1-200 already exists. Skipping.
Split FASTA file for Epitope Length 9 - Entries 1-200 already exists. Skipping.
Split FASTA file for Epitope Length 10 - Entries 1-200 already exists. Skipping.
Split FASTA file for Epitope Length 11 - Entries 1-200 already exists. Skipping.
Split FASTA file for Epitope Length 8 - Entries 201-242 already exists. Skipping.
Split FASTA file for Epitope Length 9 - Entries 201-242 already exists. Skipping.
Split FASTA file for Epitope Length 10 - Entries 201-242 already exists. Skipping.
Split FASTA file for Epitope Length 11 - Entries 201-242 already exists. Skipping.
Completed
Prediction file for Allele HLA-B*18:01 and Epitope Length 8 with Method MHCflurry (Entries 1-200) already exists. Skipping.
Prediction file for Allele HLA-B*18:01 and Epitope Length 8 with Method NetMHCpan (Entries 1-200) already exists. Skipping.
Prediction file for Allele HLA-B*18:01 and Epitope Length 8 with Method NetMHCpanEL (Entries 1-200) already exists. Skipping.
Prediction file for Allele HLA-B*18:01 and Epitope Length 9 with Method MHCflurry (Entries 1-200) already exists. Skipping.
Prediction file for Allele HLA-B*18:01 and Epitope Length 9 with Method NetMHCpan (Entries 1-200) already exists. Skipping.
Prediction file for Allele HLA-B*18:01 and Epitope Length 9 with Method NetMHCpanEL (Entries 1-200) already exists. Skipping.
Prediction file for Allele HLA-B*18:01 and Epitope Length 10 with Method MHCflurry (Entries 1-200) already exists. Skipping.
Prediction file for Allele HLA-B*18:01 and Epitope Length 10 with Method NetMHCpan (Entries 1-200) already exists. Skipping.
Prediction file for Allele HLA-B*18:01 and Epitope Length 10 with Method NetMHCpanEL (Entries 1-200) already exists. Skipping.
Prediction file for Allele HLA-B*18:01 and Epitope Length 11 with Method MHCflurry (Entries 1-200) already exists. Skipping.
Prediction file for Allele HLA-B*18:01 and Epitope Length 11 with Method NetMHCpan (Entries 1-200) already exists. Skipping.
Prediction file for Allele HLA-B*18:01 and Epitope Length 11 with Method NetMHCpanEL (Entries 1-200) already exists. Skipping.
Prediction file for Allele HLA-B*18:01 and Epitope Length 8 with Method MHCflurry (Entries 201-242) already exists. Skipping.
Prediction file for Allele HLA-B*18:01 and Epitope Length 8 with Method NetMHCpan (Entries 201-242) already exists. Skipping.
Prediction file for Allele HLA-B*18:01 and Epitope Length 8 with Method NetMHCpanEL (Entries 201-242) already exists. Skipping.
Prediction file for Allele HLA-B*18:01 and Epitope Length 9 with Method MHCflurry (Entries 201-242) already exists. Skipping.
Prediction file for Allele HLA-B*18:01 and Epitope Length 9 with Method NetMHCpan (Entries 201-242) already exists. Skipping.
Prediction file for Allele HLA-B*18:01 and Epitope Length 9 with Method NetMHCpanEL (Entries 201-242) already exists. Skipping.
Prediction file for Allele HLA-B*18:01 and Epitope Length 10 with Method MHCflurry (Entries 201-242) already exists. Skipping.
Prediction file for Allele HLA-B*18:01 and Epitope Length 10 with Method NetMHCpan (Entries 201-242) already exists. Skipping.
Prediction file for Allele HLA-B*18:01 and Epitope Length 10 with Method NetMHCpanEL (Entries 201-242) already exists. Skipping.
Prediction file for Allele HLA-B*18:01 and Epitope Length 11 with Method NetMHCpan (Entries 201-242) already exists. Skipping.
Prediction file for Allele HLA-B*18:01 and Epitope Length 11 with Method NetMHCpanEL (Entries 201-242) already exists. Skipping.
Making binding predictions on Allele HLA-B*18:01 and Epitope Length 11 with Method MHCflurry - File /home/ubuntu/epitope/work_normal/64/dfceaa8042580a81220fa7d392d531/MHC_Class_I/tmp/10-TM-FreshFrozen_tumor.MHCflurry.HLA-B*18:01.11.tsv_201-242
WARNING:tensorflow:From /opt/conda/lib/python3.8/site-packages/tensorflow/python/compat/v2_compat.py:107: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:tensorflow:From /opt/conda/lib/python3.8/site-packages/keras/src/initializers/initializers_v1.py:297: calling RandomUniform.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
/opt/conda/lib/python3.8/site-packages/keras/src/engine/training_v1.py:2359: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  updates=self.state_updates,
/opt/conda/lib/python3.8/site-packages/keras/src/engine/training_v1.py:2359: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  updates=self.state_updates,
/opt/conda/lib/python3.8/site-packages/keras/src/engine/training_v1.py:2359: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  updates=self.state_updates,
/opt/conda/lib/python3.8/site-packages/keras/src/engine/training_v1.py:2359: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  updates=self.state_updates,
/opt/conda/lib/python3.8/site-packages/keras/src/engine/training_v1.py:2359: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  updates=self.state_updates,
/opt/conda/lib/python3.8/site-packages/keras/src/engine/training_v1.py:2359: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  updates=self.state_updates,
/opt/conda/lib/python3.8/site-packages/keras/src/engine/training_v1.py:2359: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  updates=self.state_updates,
/opt/conda/lib/python3.8/site-packages/keras/src/engine/training_v1.py:2359: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  updates=self.state_updates,
WARNING:tensorflow:From /opt/conda/lib/python3.8/site-packages/tensorflow/python/ops/init_ops.py:94: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
WARNING:tensorflow:From /opt/conda/lib/python3.8/site-packages/tensorflow/python/ops/init_ops.py:94: calling Zeros.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Forcing tensorflow backend.
Making binding predictions on Allele HLA-B*18:01 and Epitope Length 11 with Method MHCflurry - File /home/ubuntu/epitope/work_normal/64/dfceaa8042580a81220fa7d392d531/MHC_Class_I/tmp/10-TM-FreshFrozen_tumor.MHCflurry.HLA-B*18:01.11.tsv_201-242 - Completed
/opt/conda/lib/python3.8/site-packages/keras/src/engine/training_v1.py:2359: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  updates=self.state_updates,
Parsing binding predictions for Allele HLA-B*18:01 and Epitope Length 8 - Entries 1-200
Parsing prediction file for Allele HLA-B*18:01 and Epitope Length 8 - Entries 1-200
Parsing prediction file for Allele HLA-B*18:01 and Epitope Length 8 - Entries 1-200 - Completed
Parsing binding predictions for Allele HLA-B*18:01 and Epitope Length 9 - Entries 1-200
Parsing prediction file for Allele HLA-B*18:01 and Epitope Length 9 - Entries 1-200
Parsing prediction file for Allele HLA-B*18:01 and Epitope Length 9 - Entries 1-200 - Completed
Parsing binding predictions for Allele HLA-B*18:01 and Epitope Length 10 - Entries 1-200
Parsing prediction file for Allele HLA-B*18:01 and Epitope Length 10 - Entries 1-200
Parsing prediction file for Allele HLA-B*18:01 and Epitope Length 10 - Entries 1-200 - Completed
Parsing binding predictions for Allele HLA-B*18:01 and Epitope Length 11 - Entries 1-200
Parsing prediction file for Allele HLA-B*18:01 and Epitope Length 11 - Entries 1-200
Parsing prediction file for Allele HLA-B*18:01 and Epitope Length 11 - Entries 1-200 - Completed
Parsing binding predictions for Allele HLA-B*18:01 and Epitope Length 8 - Entries 201-242
Parsing prediction file for Allele HLA-B*18:01 and Epitope Length 8 - Entries 201-242
Parsing prediction file for Allele HLA-B*18:01 and Epitope Length 8 - Entries 201-242 - Completed
Parsing binding predictions for Allele HLA-B*18:01 and Epitope Length 9 - Entries 201-242
Parsing prediction file for Allele HLA-B*18:01 and Epitope Length 9 - Entries 201-242
Parsing prediction file for Allele HLA-B*18:01 and Epitope Length 9 - Entries 201-242 - Completed
Parsing binding predictions for Allele HLA-B*18:01 and Epitope Length 10 - Entries 201-242
Parsing prediction file for Allele HLA-B*18:01 and Epitope Length 10 - Entries 201-242
Parsing prediction file for Allele HLA-B*18:01 and Epitope Length 10 - Entries 201-242 - Completed
Parsing binding predictions for Allele HLA-B*18:01 and Epitope Length 11 - Entries 201-242
Parsing prediction file for Allele HLA-B*18:01 and Epitope Length 11 - Entries 201-242
Parsing prediction file for Allele HLA-B*18:01 and Epitope Length 11 - Entries 201-242 - Completed
Combining Parsed Prediction Files
Completed
Creating aggregated report
Tumor clonal VAF estimated as 0.5 (calculated from user-provided tumor purity of 1.0). Assuming variants with VAF < 0.25 are subclonal
Completed
Calculating Manufacturability Metrics
Completed
Running Binding Filters
Completed
Running Coverage Filters
Completed
Running Transcript Support Level Filter
Complete
Running Top Score Filter
Completed
Running NetMHCStabPan
Completed

Done: Pipeline finished successfully. File /home/ubuntu/epitope/work_normal/64/dfceaa8042580a81220fa7d392d531/MHC_Class_I/10-TM-FreshFrozen_tumor.filtered.tsv contains list of filtered putative neoantigens.

No MHC class II alleles chosen. Skipping MHC class II predictions.
INFO:    Cleaning up image...

**Comment by riederd** [comment]
Should be fixed now in v1.4.1, please reopen if not.
