### ISSUE TITLE
Process `OptiType_RNA (test_sample)` terminated with an error exit status (1)

### ISSUE THREAD

**Issue by DecodeGenome** [icbi-lab/nextNEOpi#73]
Dear nextNEOpi developers:

I use the HPC to run nextNEOpi test sample, I got the error below and I checked the rna_mapped_1.bam and rna_mapped_2.bam file are empty. Please help to identify and solve this issue. 

Thank you very much in advance

############################################## Error messages #######################
Error executing process > 'OptiType_RNA (test_sample)'

Caused by:
  Process `OptiType_RNA (test_sample)` terminated with an error exit status (1)

Command executed:

  OPTITYPE="$(readlink -f $(which OptiTypePipeline.py))"
  MHC_MAPPED_R1=$(samtools view -c rna_mapped_1.bam)
  MHC_MAPPED_R2=$(samtools view -c rna_mapped_2.bam)
  MHC_MAPPED=$((MHC_MAPPED_R1+MHC_MAPPED_R2))
  if [ "$MHC_MAPPED" != "0" ]; then
      $OPTITYPE -i rna_mapped_1.bam rna_mapped_2.bam -e 1 -b 0.009 --rna -o ./tmp && \
      mv ./tmp/*/*_result.tsv ./test_sample_optitype_RNA_result.tsv && \
      mv ./tmp/*/*_coverage_plot.pdf ./test_sample_optitype_RNA_coverage_plot.pdf && \
      rm -rf ./tmp/
  else
      touch test_sample_optitype_RNA_result.tsv
      echo "No result" >  test_sample_optitype_RNA_coverage_plot.pdf
  fi

Command exit status:
  1

Command output:
  (empty)

Command error:
  INFO:    Environment variable SINGULARITYENV_TMPDIR is set, but APPTAINERENV_TMPDIR is preferred
  INFO:    Environment variable SINGULARITYENV_NXF_DEBUG is set, but APPTAINERENV_NXF_DEBUG is preferred
  [main_samview] fail to read the header from "rna_mapped_1.bam".

Work dir:
  /wynton/group/bivona/Analytic_tools/NextNeoPi/nextNEOpi/work/10/dd9392940df5469d3ed8ef2b821f25

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

**Comment by DecodeGenome** [comment]
Dear Dr. Dietmar,

Thanks you very much for your prompt response. Please find files you need which could help you identify the problems.

Beste Regards,

Wei
________________________________

**Comment by riederd** [comment]
Unfortunately I cannot see any files.

**Comment by DecodeGenome** [comment]
Hi Riederd, 

The files are attached here now, please let me know whether you can see them.

Thanks,
Wei

[contents.tar.gz](https://github.com/icbi-lab/nextNEOpi/files/15111893/contents.tar.gz)
[nextflow.log](https://github.com/icbi-lab/nextNEOpi/files/15111896/nextflow.log)

**Comment by riederd** [comment]
it seems that the bam files created in teh `pre_map_hla_RNA` are invalid:
`/wynton/group/bivona/Analytic_tools/NextNeoPi/nextNEOpi/work/9e/57ee15ac58f72351d24ddb25b46813/rna_mapped_1.bam`
`/wynton/group/bivona/Analytic_tools/NextNeoPi/nextNEOpi/work/9e/57ee15ac58f72351d24ddb25b46813/rna_mapped_2.bam`

what are the contents of that directory?

**Comment by DecodeGenome** [comment]
Hi, Riederd, here is the contents in /wynton/group/bivona/Analytic_tools/NextNeoPi/nextNEOpi/work/9e/57ee15ac58f72351d24ddb25b46813/

Thanks,

[9e_contents.tar.gz](https://github.com/icbi-lab/nextNEOpi/files/15112606/9e_contents.tar.gz)

**Comment by DecodeGenome** [comment]
Hi Riederd,
We defined "tmpDir: /wynton/scratch/wwu888/nextNEOpi" (see in nextflow.log, line="Apr-24 21:11:40.257 [main] INFO  nextflow.script.BaseScript") , why the nextNeopi is trying to create temporay file to "/scratch/wwu888/" here. Even using this directory, I checked the directory "scratch/wwu888", it has sufficient memory there.  How to ask the pipeline to use tmpDir:/wynton/scratch/wwu888/nextNEOpi? 

Thanks,


<img width="583" alt="Screenshot 2024-04-25 at 11 30 26 AM" src="https://github.com/icbi-lab/nextNEOpi/assets/15950088/9bed56f5-1a6a-49a5-91e0-da076754d219">

**Comment by riederd** [comment]
Hi, it is not `nextNEOpi` directly trying to write into `/scratch/wwu888` it is the `yara_mapper` which reads the ENV variable `$TEMPDIR` and uses that value to write temporary files. I guess you have `/scratch/wwu888` set as `$TEMPDIR` on your system, however this is not mounted into the singularity container that runs the `yara_mapper`. 

So one thing you could try is to set `$TEMPDIR` to the same directory you are using as `tmpDir` in `nextNEOpi` before launching the pipeline, i.e.:
`$ export TEMPDIR=/wynton/scratch/wwu888/nextNEOpi`

**Comment by DecodeGenome** [comment]
Hi Riederd,
I tried your suggestion, it is the same error.  yara_mapper still reads the ENV as /scratch/wwu888.  I checked /scratch/wwu888, it does contain singularity.  Any other sugguestions?

Thanks,
Wei

**Comment by DecodeGenome** [comment]
Hi,
The problem was solved with setting: "export SINGULARITYENV_TMPDIR=/wynton/scratch/wwu888/nextNEOpi". However, when running the command: 
![image](https://github.com/icbi-lab/nextNEOpi/assets/15950088/c3a2f0a4-7bc6-419e-aeb7-e2643d2098cd)
a new error occured, see #17.

Thanks,

Wei

**Comment by riederd** [comment]
Can you provide more details

**Comment by riederd** [comment]
Closing: no more details provided. Please check if v1.4.1 is fixing this.
