### ISSUE TITLE
pVACtools_generate_protein_seq (test_sample)` terminated with an error exit status (1)

### ISSUE THREAD

**Issue by DecodeGenome** [icbi-lab/nextNEOpi#74]
Hi nextNEOpi developer,

While I ran command line for test sample, it gave me an error as followings, I attached contents from /wynton/group/bivona/Analytic_tools/NextNeoPi/nextNEOpi/work/c5/4d38fd64e93256a050d78f2774d3dd and file from .nextflow.log for your information.  Please help to resolve this issue.

Thanks,

Wei

################################## Error message ####################
Error executing process > 'pVACtools_generate_protein_seq (test_sample)'

Caused by:
  Process `pVACtools_generate_protein_seq (test_sample)` terminated with an error exit status (1)

Command executed:

  pvacseq generate_protein_fasta \
      -p test_sample_vep_phased.vcf.gz \
      -s test_sample_tumor \
      -d full \
      test_sample_vep_somatic_gx.vcf.gz \
      31 \
      test_sample_long_peptideSeq.fasta

Command exit status:
  1

Command output:
  Converting VCF to TSV

Command error:
  INFO:    Environment variable SINGULARITYENV_TMPDIR is set, but APPTAINERENV_TMPDIR is preferred
  INFO:    Environment variable SINGULARITYENV_NXF_DEBUG is set, but APPTAINERENV_NXF_DEBUG is preferred
  Converting VCF to TSV
  VCF doesn't contain VEP FrameshiftSequence annotations. Please re-annotate the VCF with VEP and the Wildtype and Frameshift plugins.

Work dir:
  /wynton/group/bivona/Analytic_tools/NextNeoPi/nextNEOpi/work/c5/4d38fd64e93256a050d78f2774d3dd

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

[April_29_nextflow.log](https://github.com/icbi-lab/nextNEOpi/files/15157053/April_29_nextflow.log)
[c5_contents.tar.gz](https://github.com/icbi-lab/nextNEOpi/files/15157054/c5_contents.tar.gz)
[vep_cache_plugins.tar.gz](https://github.com/icbi-lab/nextNEOpi/files/15157058/vep_cache_plugins.tar.gz)

**Comment by riederd** [comment]
Can you post the `vcf.gz` files from the c5 dir, e.g. create the `tar.gz` with the `--dereference` tar option.

**Comment by DecodeGenome** [comment]
Hi Riederd, please see the attachment. Thanks.
[c5_vcf_contents.tar.gz](https://github.com/icbi-lab/nextNEOpi/files/15167117/c5_vcf_contents.tar.gz)

**Comment by riederd** [comment]
It seems that you are lacking the `Frameshift.pm` and the `Wildtype.pm` plugins in `vep_cache/Plugins` . They should have been installed on the first run of the pipeline, see:

https://github.com/icbi-lab/nextNEOpi/blob/fe7b21cdc0b97aae38195e5f5ac1b9851674f6b1/nextNEOpi.nf#L3255-L3291

Did you notice any error message regarding the `installVEPplugins` proccess?

Anyway, you may try to copy them manually from the `assets` folder of `nextNEOpi`  to the `vep_cache/Plugins` dir, or you can delete the `/wynton/group/bivona/Analytic_tools/NextNeoPi/nextNEOpi/resources/databases/.110_plugins_ok.chck` file and rerun the pipeline.

**Comment by DecodeGenome** [comment]
Hi Riederd, Thank you very much. For installVEPplugins process, I did not see any error messages.  I now copies these two files, and hopefully everything is ok.
Best Regards!

**Comment by riederd** [comment]
Seems to be fixed. Closing it.
