### ISSUE TITLE
pVACseq (test_sample)` terminated with an error exit status (1)

### ISSUE THREAD

**Issue by DecodeGenome** [icbi-lab/nextNEOpi#75]
Hi nextNEOpi developers:

Thank you very much for your previous support.
I am running the test sample using  nextNEOpi, it appears to create results, but at the end, there is an error:

Error executing process > 'pVACseq (test_sample)'

Caused by:
  Process `pVACseq (test_sample)` terminated with an error exit status (1)

Command executed:

  pvacseq run \
      --iedb-install-directory /opt/iedb \
      -t 10 \
      -p test_sample_vep_phased.vcf.gz \
      -e1 8,9,10,11 \
      -e2 15,16,17,18,19,20,21,22,23,24,25 \
      --normal-sample-name test_sample_normal \
      --tumor-purity 0.53 \
       \
      --netmhc-stab \
      --binding-threshold 500 --top-score-metric median --minimum-fold-change 0.0 --normal-cov 5 --tdna-cov 10 --trna-cov 10 --normal-vaf 0.02 --tdna-vaf 0.25 --trna-vaf 0.25 --expn-val 1 --maximum-transcript-support-level 1 \
      test_sample_vep_somatic_gx.vcf.gz test_sample_tumor HLA-C*06:02 NetMHCpan NetMHCpanEL MHCflurry MHCflurryEL NetMHCIIpan NetMHCIIpanEL ./
  
  if [ -e ./MHC_Class_I/test_sample_tumor.filtered.tsv ]; then
      mv ./MHC_Class_I/test_sample_tumor.filtered.tsv ./MHC_Class_I/test_sample_tumor_HLA-C*06:02.filtered.tsv
  fi
  if [ -e ./MHC_Class_I/test_sample_tumor.all_epitopes.tsv ]; then
      mv ./MHC_Class_I/test_sample_tumor.all_epitopes.tsv ./MHC_Class_I/test_sample_tumor_HLA-C*06:02.all_epitopes.tsv
  fi
  if [ -e ./MHC_Class_II/test_sample_tumor.filtered.tsv ]; then
      mv ./MHC_Class_II/test_sample_tumor.filtered.tsv ./MHC_Class_II/test_sample_tumor_HLA-C*06:02.filtered.tsv
  fi
  if [ -e ./MHC_Class_II/test_sample_tumor.all_epitopes.tsv ]; then
      mv ./MHC_Class_II/test_sample_tumor.all_epitopes.tsv ./MHC_Class_II/test_sample_tumor_HLA-C*06:02.all_epitopes.tsv
  fi
.............................................. 

Work dir:
  /wynton/group/bivona/Analytic_tools/NextNeoPi/nextNEOpi/work/f6/58dc606a49d04d69929dfb59b386d5

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

As usual, I aattached the compressed file from Word dir for your information, hopefully, you can provide suggestions or solutions.

Best,

Wei
[58dc_contents.tar.gz](https://github.com/icbi-lab/nextNEOpi/files/15359672/58dc_contents.tar.gz)

**Comment by riederd** [comment]
This should be fixed now by `nextNEOpi v1.4.1` which uses now pVACtools 4.1.1(see also #43, #60, #66)
