### ISSUE TITLE
Error executing process > 'install_IEDB (Install IEDB)'

### ISSUE THREAD

**Issue by Xiao-Zhong** [icbi-lab/nextNEOpi#77]
Hi, Sorry for bothering you again! First, thanks!

I'm slowly pushing forward in running your pipeline, and have encountered the issues below:
1, as posted, the pipeline failed to install IEDB, due to `cd /opt/iedb/`. Here the directory is unavailable in our HPC.

`Command error:
  .command.sh: line 5: cd: /opt/iedb/: No such file or directory`

See the details in:
[nextflow.log](https://github.com/user-attachments/files/15903325/nextflow.log)

2, can I ask how does the pipeline install GATK4 via conda profile? In the 'profiles.config' file, I only can see GATK3-related code.
`            withLabel: GATK3 {
                conda = 'bioconda::gatk=3.8'
                params.gatk3_conda_url = "https://anaconda.org/bioconda/gatk/3.8/download/noarch/gatk-3.8-hdfd78af_11.tar.bz2"
            }`
            
I've manually installed the latest GATK 4 (`gatk-4.5.0.0`), and looks working, however I'm unsure if the version is compatible with your pipeline. 

Regards,
Xiao

**Comment by riederd** [comment]
we recommend to run the pipeline using singularity `-profile singularity`, did you try this?
With conda or local installation of the tools we see such problems.

**Comment by Xiao-Zhong** [comment]
Thank you, Dietmar!
I would like to try singularity, however it's unavailable on the HPC I'm using and I haven't managed to install singularity without root permission.

I've installed a few dependencies manually after repeatedly running your pipeline and finding errors, but got stuck at 'Install IEDB'.

OK. I've asked IT team if they're happy to install singularity, will try to work around the issues via checking your code or will test your pipeline on a virtual machine with root permission. Hopefully either way will work!

Regards,
Xiao

**Comment by Xiao-Zhong** [comment]
Hi, Just let you know nextNEOpi ran without the problem with -profile singularity,cluster, after I installed singularity by conda. Thanks!

**Comment by riederd** [comment]
I'm assuming this to be solved.
