### ISSUE TITLE
License not recognized, Singularity image pull error

### ISSUE THREAD

**Issue by CSree** [icbi-lab/nextNEOpi#79]
Hi, 

1. I downloaded the latest mi.license, however still it is not recognized by the pipeline.

<img width="646" alt="Screenshot 2024-08-09 at 12 12 52 PM" src="https://github.com/user-attachments/assets/9b80e9f3-0b5c-4dde-9c52-66484afc9e6c">

2. Running with tcr - false, After 7hrs, this is the error:

<img width="757" alt="Screenshot 2024-08-09 at 12 04 19 PM" src="https://github.com/user-attachments/assets/15a58aa5-6191-49e4-a1d4-c20781d209a9">

thanks in advance
Chai

**Comment by riederd** [comment]
Hi,

1.
The mixcr license file needs to be passed to the `nextNEOpi` pipeline via `--MIXCR_lic /path/to/yourwonderful/mi.licences`

and it should look like:

```
$ cat mi.license | tr '[A-Z]' 'X'
X-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

2.
it seems you have connection issues form the machine that runs the strelka process. I just tested manually here and it works fine:

```
$ singularity pull --name strelka_test.sif https://depot.galaxyproject.org/singularity/strelka:2.9.10--h9ee0642_1
INFO:    Downloading network image
78.2MiB / 78.2MiB [==================================================================================================================================================] 100 % 5.5 MiB/s 0s
$ ls -l strelka_test.sif 
-rwxr-xr-x 1 user users 81948672 Aug 12 15:52 strelka_test.sif

```

HTH

**Comment by riederd** [comment]
no feedback. I'm closing the issue for now, please feel free to open it again
