### ISSUE TITLE
--WES false error

### ISSUE THREAD

**Issue by gilsonmm** [icbi-lab/nextNEOpi#80]
Good afternoon,

I am using WGS data in bam format and when I attempt to use --WES false the pipeline fails with an error. I get this error whether --WES false is stated in the command line or if it is changed in the params.config file. I attached the output with the error, shell script contents and the params.config file. I am not sure if the error is on my end or within the pipeline, if --WES is set to true the pipeline finishes. Please let me know if you need more info/documents.

Thank you!

Shell:

#!/bin/bash

module load java
module load singularity
export SINGULARITY_CACHEDIR=/data/gilsonmm/.singularity
module load nextflow/22.10.2
module load bowtie2

nextflow run nextNEOpi.nf --batchFile first_batchFile_BAM.csv -config conf/params.config --accept_license  --outputDir /data/gilsonmm/neoantigen/nextNEOpi/test_results/ --trim_adapters true --trim_adapters_RNAseq true --use_NetChop false --CNVkit false --tmpDir /data/gilsonmm/neoantigen/temporary -profile singularity,cluster

Output:
[slurm-37354970.out.gz](https://github.com/user-attachments/files/17283080/slurm-37354970.out.gz)

Params.config:
[params.config.gz](https://github.com/user-attachments/files/17283082/params.config.gz)

**Comment by riederd** [comment]
Hi,

I'm afraid I need more information to track this down. Can you please provide the `first_batchFile_BAM.csv` file and the `.nextflow.log` file?

**Comment by gilsonmm** [comment]
Yes I can!

[first_batchFile_BAM.csv](https://github.com/user-attachments/files/17293012/first_batchFile_BAM.csv)
[nextflow.log](https://github.com/user-attachments/files/17293081/nextflow.log)

**Comment by riederd** [comment]
I tried to reproduce this but I did not run in to the same issue. Which version of the pipeline do you use?

**Comment by mantczakaus** [comment]
Hi, I think I had an issue like that as well. I don't have logs anymore but I can reproduce if necessary. The issue I had was that even though you specify WES=false, the workflow checks for exome capture kit. As a workaround, I provided in the params.config:
```
  WES             = false  // if false assume WGS, attention long runtimes
  exomeCaptureKit = "sureSelectV6"
```
and then I kept the paths to sureSelectV6 in the resources.config
```
exomeCaptureKits {
    sureSelectV6 {
        BaitsBed           = "${params.resourcesBaseDir}/human/ExomeCaptureKits/Agilent/hg38/S07604514_Covered.bed"
        RegionsBed         = "${params.resourcesBaseDir}/human/ExomeCaptureKits/Agilent/hg38/S07604514_Regions.bed"
    }
}
```

**Comment by gilsonmm** [comment]
Thank you for your suggestion! I had mine set up exactly like what you have and it doesn't appear that my issue is related to that.

**Comment by riederd** [comment]
Thanks for reporting and your feedback @mantczakaus and @gilsonmm . I could now reproduce the issue and pushed a fix, please check and let me know if it works.

**Comment by gilsonmm** [comment]
Thank you so much! It looks like it is running correctly!
