### ISSUE TITLE
Using the pipeline on cell line data

### ISSUE THREAD

**Issue by GMFranceschini** [icbi-lab/nextNEOpi#81]
Dear developers,
Could you advise me on running the pipeline on cancer cell line data? 
In that case, we don't have the normal DNA, could we use a random individual or a panel of normals? I know it's not an ideal setting, but I would still like to try to get neoantigens.
Thank you in advance

**Comment by riederd** [comment]
Hi, thanks for your interest in `nextNEOpi`. Technically you may use DNA from any normal and in addition a panel of normals and the pipeline would run, however this will most likely give you random results, I'd not advise to do so unless it is just for playing/testing.
