### ISSUE TITLE
New version of nextNEOpi

### ISSUE THREAD

**Issue by mantczakaus** [icbi-lab/nextNEOpi#84]
Hi
I was wondering when we could expect nextNEOpi2 and what differences we can expect between version 1 and 2. As you are aware, I've been experiencing many performance issues while running nextNEOpi on WGS data and I am curious whether this will be addressed in the new version. We are happy to test the new version on our WGS data if it helps.
Best wishes,
Magda

**Comment by riederd** [comment]
Thank you for your interest in nextNEOpi2 and your offer to assist with testing. We are indeed actively working on the next iteration of nextNEOpi, and we appreciate your patience as we finalize this major update.

While we don't have a firm release date yet, we can share some planned improvements:

* DSL2 Migration: We are porting nextNEOpi2 to DSL2 and integrate it with the nf-core ecosystem. 
* NeoFuse Progress: The NeoFuse component is nearing completion (ported from bash based to nextflow DSL2 using now multiple binding prediction tools). 
* Mouse Support: nextNEOpi2 will include mouse as a supported organism
* Performance Enhancements: We are actively addressing the performance issues you experienced with nextNEOpi on WGS data. This includes runtime improvements for large datasets.
* TCR Binding Prediction: A new addition to nextNEOpi2 will be the integration of TCR binding prediction
