### ISSUE TITLE
VEPTab and VEPVcf process got invalid output file

### ISSUE THREAD

**Issue by origyZ** [icbi-lab/nextNEOpi#86]
hi, i am running nextNEOpi with Testdata which got from Readme.md, but i got the error in the clonality process:
`
ERROR ~ Error executing process > 'clonality (sample1)'

Caused by:
  Process `clonality (sample1)` terminated with an error exit status (1)

Command executed:

  mkCCF_input.py \
      --PatientID sample1_tumor \
      --vcf sample1_hc_vep.vcf.gz \
      --seg sample1.cnvs.txt \
      --purity sample1.purityploidy.txt \
      --min_vaf 0.01 \
      --result_table sample1_segments_CCF_input.txt && \
  Rscript \
      CCF.R \
      sample1_segments_CCF_input.txt \
      sample1_CCFest.tsv \

Command exit status:
  1

Command output:
  (empty)

Command error:
  Error in `[<-`(`*tmp*`, i, , value = absCCF2(indata[i, ])) :
    subscript out of bounds
  Calls: getCCF
  Execution halted

Work dir:
  /data/work_test/80/c970f1ac6b072c87e6a699d5c42d34

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

 -- Check '/data/work_test/nextneopi.log' file for details
`
Then, i checked the input of clonality and found that the file sample1_hc_vep.vcf.gz which producted by VEPVcf process is invalid(only comments in this file). I also checked the output file producted by VEPTab, and got the same result.
Could you tell me how to solve this problem?
Thank you very much in advance!

**Comment by kuzala** [comment]
Hi, sorry to reopen the issue but I'm facing the same problem with version 1.5.0 while using singularity profile. I couldn't understand why this error happens and find a solution. Could you please tell me how I can fix this very same issue? Thank you very much
