### ISSUE TITLE
how to install the software

### ISSUE THREAD

**Issue by Donbbit** [icbi-lab/nextNEOpi#88]
Hello,  
I am a bit confused about installing this software. Is there a detailed guide on how to install it using Conda? Also, where can I find the mentioned "Manual Installation" instructions? Furthermore, the link https://apps-01.i-med.ac.at/resources/nextneopi/ seems to be inaccessible. Could you please provide an updated link?  
Thank you very much for your help.

**Comment by riederd** [comment]
Hi, thanks for your interest in `nextNEOpi`

The easiest way to run the `nextNEOpi` is using singularity. Manual installation of the software tools used by the pipeline not recommended it is very likely that you get dependency issues. We also discourage users from running the pipeline in conda mode.


You may want to follow the installation instructions as mentioned in the README.md under `1. Installation`

Briefly:

1. install nextflow
2. install singularity
3. download and extract `nextNEOpi`  e.g. <https://github.com/icbi-lab/nextNEOpi/archive/refs/tags/v1.4.1.tar.gz>
4. Download the resources bundle file from <https://apps-01.i-med.ac.at/resources/nextneopi/nextNEOpi_1.4_resources.tar.gz>
5. extract the resources bundle in a location that has > 50GB of free disk space
6. change `resourcesBaseDir` in  `conf/params.config` to that location
7. run the pipeline as described under `2. Usage`


HTH
