### ISSUE TITLE
Wrong merge input with `gatherMutect1VCFs`

### ISSUE THREAD

**Issue by phoenix-yyj** [icbi-lab/nextNEOpi#89]
In the Process `gatherMutect1VCFs`,

the code is 
```
 gatk --java-options ${java_opts} MergeVcfs \\
        --TMP_DIR ${params.tmpDir} \\
        -I ${vcf[0].join(" -I ")} \\
        -O ${meta.sampleName}_mutect1_raw.vcf.gz
```
why the input is `vcf[0].join(" -I ")`

that means the input is just one file 

maybe should like `vcf.join(" -I ")`

**Comment by riederd** [comment]
Hi,

the input channel `Mutect1scattered_out_ch0` is defined at:
https://github.com/icbi-lab/nextNEOpi/blob/f6300dd1eb8e1db07f4ed2f3dba0ae56f2da5d70/nextNEOpi.nf#L2733

you can appreciate that `vcf` consists of [0] `vcf.gz`  and [1] `vcf.gz.idx` (`path("${meta.sampleName}_${intervals}.raw.{vcf.gz,vcf.gz.idx}")`)

HTH
